#!/bin/bash
# Generated by build.sh from src/. Edit module sources, then rebuild this release file.

# ============================================================
#  VPS 开荒脚本 V3.52.0 — 银趴火山帮
#  功能：SSH管理 / Fail2ban / BBR TCP 调优
#  V3.52.0: BBR 智能向导替换为单线程自适应 BDP 与可选 policer 拐点扫描
#  V3.51.2: 修复 Debian DNS/DHCP 与 CentOS 7 旧版 NetworkManager/ifcfg 兼容
#  V3.51.1: 修复 Ubuntu Netplan 重复修改网卡时合并旧路由配置
#  V3.51.0: 新增跨发行版网卡静态 IPv4、网关、掩码与 DNS 管理
#  V3.50.9: 修复严格模式自动回滚误失败及退出严格模式的认证残留
#  V3.50.8: 合并上游 DDNS 双栈结果校验与多 IP 出口源地址安全切换
#  V3.50.7: 合并上游 DDNS 凭据明文输入，修正 smoke 的旧事务函数名
#  V3.50.6: 合并上游 BBR 内存/转发策略、tc 自动恢复与 DDNS 事务加固
#  V3.50.5: 修复公钥增删改的间歇性误判并发修改、DDNS 事务始终失败的 PATH 遮蔽
#  V3.50.4: 修复需要密码的 sudo 管理员被误判为无 root 权限
#  V3.50.3: 修复 systemd socket 激活的 sshd 无法通过 sshd_config 修改端口
#  V3.50.2: 修复离线包元数据变量作用域 bug，清理死代码与 shellcheck 全部警告
#  V3.50.1: 合并上游 tc 限速修复：兼容 mq 网卡，支持确认后接管或删除外部 root qdisc
#  V3.50.0: 强化 SSH、防火墙、用户、回滚、离线安装与定时任务的事务一致性
#  V3.20.3: 生成密钥对后可选择 root、指定登录用户或不写入服务器
#  V3.20.2: 合并上游离线安装包与 HTTPS 自动校时，并修复交互会话锁释放
#  V3.20.1: SSH 公钥查看/删除支持指定用户，删除新增管理入口预演、备份与自动回滚
#  V3.20.0: SSH 新增严格模式、指定用户添加公钥及带剩余管理入口校验的登录撤权
#  V3.11.9: 修复撤销管理员后 sudo 列表退出码导致的用户类型误判
#  V3.11.8: 修复安全体检误报 root 密码登录并补充键盘交互组合判断
#  V3.11.7: 用户管理新增提升现有管理员与撤销管理员权限
#  V3.11.6: 用户管理新增 root、普通用户及 sudo 管理员密码修改
#  V3.11.5: 修复用户列表调用不存在的暂停函数导致页面瞬间返回
#  V3.11.4: 用户管理新增安全删除，可选择保留或删除主目录工作空间
#  V3.11.3: 新增普通/sudo 管理员用户创建、事务回滚与非 root 提权引导
#  V3.11.2: 将文档、安装清单与自更新源切换到长期维护 Fork
#  V3.11.1: 修复 SSH/Fail2ban 端口同步、更新临时文件、回滚并发、DDNS 事务与 Windows 行尾
#  V3.11.0: 新增多来源 HTTPS 时间同步，适配 UDP/123 被封锁
#  V3.10.9: 修复零公钥时 grep 计数重复输出导致首页状态断行
#  V3.10.8: 修复 Caddy 嵌套块误列为站点及后端显示不完整
#  V3.10.7: 续费提醒支持到期次日存活自动顺延
#  V3.10.6: DDNS 新增代理分享链接地址替换工具
#  V3.10.5: 修复 DDNS 双栈域名混用与交叉残留记录
#  V3.10.4: IMPART OPS 首页改用响应式 ANSI Shadow 块状字幅
#  V3.10.3: STUN 检测结果增加动态解释与使用建议
#  V3.10.2: 替换不稳定的 Sipgate STUN 默认节点
#  V3.10.1: Cloudflare DDNS API Token 输入改为明文显示
#  V3.10.0: 新增 STUN、多端口 UDP 探测与 NAT 类型判定
#  V3.9.48: 修复旧版 tc 限速规则因缺少状态文件而无法修改
#  V3.9.47: 修复进程替换安装导致脚本截断及测试污染系统快捷键
#  V3.9.46: 修复防火墙、NFT、恢复、Swap、DDNS、Caddy、换源及系统配置事务错误
#  V3.9.44: 修复监控通知假成功、续费自动推进、冷却失效、cron 并发和多网卡流量重复统计
#  V3.9.43: 修复 DDNS 二次确认漏报、失败状态覆盖成功 IP、并发执行及 cron 误匹配
#  V3.9.42: DDNS 检测到本机公网 IP 变化时即使 DNS 已同步也记录变更并推送 Telegram
#  V3.9.41: 修复 DDNS 首页变更记录可能显示旧 IP 状态的问题，按最新状态过滤并比较日志/状态时间
#  V3.9.40: 自更新优先锁定 GitHub main commit 下载，避免 raw/CDN 缓存导致脚本与 SHA256 不一致
#  V3.9.39: DDNS 支持自定义检测间隔分钟数，安装、修改和恢复自动更新时写入对应 cron
#  V3.9.38: DDNS IPv6 外部探测失败时回退读取本机全局 IPv6，避免有公网 IPv6 但 curl -6 失败时报错
#  V3.9.37: DDNS 新增华为云 DNS 服务商，支持 AK/SK 签名更新 A / AAAA 记录
#  V3.9.36: 流量监控记录上次网卡计数，重启/计数重置后把已用流量滚入持久 offset
#  V3.9.35: 修复监控配置 source 执行、SSH Include 覆盖、NFT flush ruleset 与 HTML 转义
#  V3.9.34: 修复重启/网卡计数重置后流量当前周期被旧基线钳成 0
#  V3.9.33: DDNS 首页按 IPv4 A / IPv6 AAAA 分别展示最新状态和最后变更
#  V3.9.32: 修复 DDNS 菜单最后变更时间变量误用 LC_TIME 导致 locale warning
#  V3.9.31: DDNS 支持 IPv4 A 与 IPv6 AAAA 分别设置，可同域名或不同子域名同时更新
#  V3.9.30: SSH 改端口流程改为先确认新端口可登录，再决定是否关闭旧端口
#  V3.9.29: 修复每日日报和续费提醒同日重复推送，并转义 Telegram HTML 主机显示名
#  V3.9.28: 首页采用清爽运维风，缩小 IMPART OPS 字幅并增加副标题
#  V3.9.27: 统一所有交互界面标题为 VPS TOOLS · 版本号 + 当前模块名
#  V3.9.26: 流量监控启用时新增“是否清除旧记录”确认，保留或重置统计由用户决定
#  V3.9.25: 安全与诊断工具箱新增系统 hostname 修改，自动校验并同步 /etc/hostname 与 /etc/hosts
#  V3.9.24: 续费提醒新增“我已续费”，确认后跳过当前周期并从下一周期继续提醒
#  V3.9.23: 日报、流量、续费、资源告警子页均支持立即推送当前实时快照
#  V3.9.22: 重排监控告警中心流程，新增快速启用、通知/日报/流量/续费/资源/高级独立子页
#  V3.9.21: 日报启用时自动安装精确定时任务，避免 23:59 等时间被 10 分钟轮询错过
#  V3.9.20: 监控告警增加趋势摘要与告警分级，日报/测试快照同步展示
#  V3.9.19: 监控告警中心增强，支持冷却/静默/恢复通知/检查项开关/最近告警记录
#  V3.9.18: 新增配置体检与诊断包入口，并引入 manifest 支撑更新校验
#  V3.9.17: 服务管理统一使用 systemd_available 检测，减少 cron/容器环境误判
#  V3.9.16: 流量监控阈值设置与启用逻辑拆分，避免修改阈值时重置今日与周期累计
#  V3.8.6: 新增配置导出/导入与统一回滚中心入口
#  V3.8.5: 新增从 URL 拉取 Compose 文件、自动校验并部署的入口，
#          支持先预览再落盘执行 `docker compose up -d --pull always`
#  V3.8.4: 新增 Docker Engine 一键安装、容器生命周期管理、日志/Shell，
#          Compose 服务安全升级与普通容器镜像更新检查
#  V3.8.3: 新增跨发行版常用软件多选安装，以及带容器检测、脚本语法校验、
#          固定确认词和 SSH 参数继承的一键 DD / Linux 系统重装安全向导
#  V3.8.2: 统一剩余子页面：BBR 多级向导、Fail2ban、Swap、换源、日志、
#          NFT 访问控制及安装页面全部接入响应式菜单、提示和暂停组件
#  V3.8.1: 重构响应式终端界面：宽/窄屏自适应、统一状态仪表盘、菜单、提示，
#          支持 NO_COLOR 与非交互终端，压缩重复标题并改善主要模块导航
#  V3.8.0: 源码模块化并生成单文件发行版；新增跨发行版/故障注入测试、备份保留、
#          配置变更预览、资源健康检查和系统更新管理
#  V3.7.0: 新增系统安全体检、登录安全日志、网络诊断、统一配置备份恢复、
#          操作审计、防断联延迟回滚、DNS 后端适配、脚本版本回滚与 SHA256 校验
#  V3.6.3: IPv4/IPv6 配置菜单新增“设置 IPv6 优先”，可恢复系统默认地址优先级
#  V3.6.2: BBR 模块增强：sysctl 权限探测无副作用、tc service 动态找 tc/网卡、
#          不支持 sysctl 参数注释持久化、Alpine 内核包安装需确认、增加诊断入口
#  V3.6.1: 修复删除最后一个 SSH 公钥不生效、DDNS 备用日志路径不生效、
#          nftables 应用失败误报成功、initcwnd 无网关默认路由失败
#  V3.6.0: Fail2ban 加 mode=aggressive(纯公钥机抓扫描)、journalmatch 双服务名
#          (兼容 Debian ssh / RedHat sshd)、jail.local 已存在改为备份后重写(原跳过)
#  V3.5.9: SSH改端口/配置失败自动回滚、改端口延后删旧(防锁死)、防火墙卸载不再
#          flush全表(只删自身规则)、DDNS IPv4严格校验、服务操作统一svc_*封装、
#          默认网卡用 ip route get、Caddy 配置临时验证通过才写入
#  V3.5.8: 修复 bbr-tune.sh 独立版缺失 4 个辅助函数(ensure_conntrack_module/
#          svc_daemon_reload/svc_enable/svc_disable)，独立运行限速/场景预设不再中断
#  V3.5.7: DDNS 状态区增加「最后一次 IP 变更时间 + 新旧 IP」显示
#  V3.5.6: 新增 UDP 缓冲(QUIC/Hysteria2)、场景预设加端口范围/tw_buckets/file-max
#          防高并发端口耗尽、应用场景预设后检测代理 service LimitNOFILE
#  V3.5.5: BBR 限速改 htb 整形+fq pacing(保 BBR)、burst 随速率缩放、
#          切换预设复位残留场景键、新增 32MB 缓冲档、修 BDP 双截断
# ============================================================

# ── 解释器守卫：本脚本依赖 bash（数组 / [[ ]] / here-string 等）──
# 仅用 POSIX 语法编写，确保在 ash/dash 下也能解析并 fail-fast。
if [ -z "$BASH_VERSION" ]; then
    if command -v bash >/dev/null 2>&1; then
        exec bash "$0" "$@"
    fi
    echo "本脚本需要 bash 运行，当前 shell 不是 bash 且系统未安装 bash。"
    echo "请先安装 bash 后重试："
    echo "  Alpine:   apk add bash"
    echo "  OpenWrt:  opkg update && opkg install bash"
    echo "  Debian:   apt-get install -y bash"
    echo "  CentOS:   yum install -y bash"
    exit 1
fi

SSHD_CONFIG="/etc/ssh/sshd_config"
SSHD_MANAGED_BEGIN="# BEGIN VPS-TOOLS SSH SETTINGS"
SSHD_MANAGED_END="# END VPS-TOOLS SSH SETTINGS"
# Ubuntu 22.10+/Debian 新版 openssh-server 默认用 systemd socket 激活 sshd，
# sshd_config 的 Port 对监听端口不一定生效，必须显式覆盖 ssh.socket 的 ListenStream
SSHD_SOCKET_OVERRIDE_DIR="/etc/systemd/system/ssh.socket.d"
SSHD_SOCKET_OVERRIDE_FILE="$SSHD_SOCKET_OVERRIDE_DIR/99-vps-tools-port.conf"
# 优先使用 /root/.ssh/authorized_keys，兼容系统预装公钥路径
AUTH_KEYS="${HOME}/.ssh/authorized_keys"
[ "$(id -u)" = "0" ] && AUTH_KEYS="/root/.ssh/authorized_keys"
VPS_DATA_DIR="/var/lib/vps-tools"
# shellcheck disable=SC2034 # used by management modules in the concatenated release script
VPS_BACKUP_DIR="$VPS_DATA_DIR/backups"
# shellcheck disable=SC2034 # used by management modules in the concatenated release script
VPS_VERSION_DIR="$VPS_DATA_DIR/versions"
VPS_AUDIT_LOG="/var/log/vps-tools-audit.log"
VPS_BACKUP_KEEP="${VPS_BACKUP_KEEP:-20}"
case "$VPS_BACKUP_KEEP" in ''|*[!0-9]*) VPS_BACKUP_KEEP=20 ;; esac
[ "$VPS_BACKUP_KEEP" -ge 1 ] || VPS_BACKUP_KEEP=20

if [ -n "${NO_COLOR:-}" ] || [ "${TERM:-}" = "dumb" ] || [ ! -t 1 ]; then
    RED="" GREEN="" YELLOW="" BLUE="" CYAN="" BOLD="" DIM="" NC=""
else
    RED=$'\033[0;31m'
    GREEN=$'\033[0;32m'
    YELLOW=$'\033[1;33m'
    BLUE=$'\033[0;34m'
    CYAN=$'\033[0;36m'
    BOLD=$'\033[1m'
    DIM=$'\033[2m'
    NC=$'\033[0m'
fi

info()  { echo -e "  ${GREEN}✓${NC}  $1"; }
warn()  { echo -e "  ${YELLOW}!${NC}  $1"; }
error() { echo -e "  ${RED}×${NC}  $1"; }

vps_tools_ssh_connection() {
    local RAW="${VPS_TOOLS_SSH_CONNECTION:-${SSH_CONNECTION:-}}"
    local CLIENT_IP CLIENT_PORT SERVER_IP SERVER_PORT EXTRA
    [ -n "$RAW" ] || return 1
    read -r CLIENT_IP CLIENT_PORT SERVER_IP SERVER_PORT EXTRA <<< "$RAW"
    [ -z "$EXTRA" ] || return 1
    [ -n "$CLIENT_IP" ] && [ -n "$SERVER_IP" ] || return 1
    [ "${#CLIENT_IP}" -le 64 ] && [ "${#SERVER_IP}" -le 64 ] || return 1
    case "$CLIENT_IP$SERVER_IP" in *[!0-9A-Fa-f:.]*) return 1 ;; esac
    case "$CLIENT_PORT:$SERVER_PORT" in
        *[!0-9:]*|:*|*:) return 1 ;;
    esac
    [ "$CLIENT_PORT" -ge 1 ] 2>/dev/null && [ "$CLIENT_PORT" -le 65535 ] \
        && [ "$SERVER_PORT" -ge 1 ] 2>/dev/null && [ "$SERVER_PORT" -le 65535 ] \
        || return 1
    printf '%s %s %s %s\n' \
        "$CLIENT_IP" "$CLIENT_PORT" "$SERVER_IP" "$SERVER_PORT"
}

vps_tools_ssh_client_ip() {
    local CONNECTION CLIENT_IP
    CONNECTION=$(vps_tools_ssh_connection) || return 1
    read -r CLIENT_IP _ <<< "$CONNECTION"
    printf '%s\n' "$CLIENT_IP"
}

vps_tools_ssh_family() {
    local CLIENT_IP
    case "${VPS_TOOLS_SSH_FAMILY:-}" in
        4|6) printf '%s\n' "$VPS_TOOLS_SSH_FAMILY"; return 0 ;;
        "") ;;
        *) return 1 ;;
    esac
    CLIENT_IP=$(vps_tools_ssh_client_ip) || return 1
    case "$CLIENT_IP" in
        *:*) printf '6\n' ;;
        *.*) printf '4\n' ;;
        *) return 1 ;;
    esac
}

audit_action() {
    local ACTION="$1" RESULT="${2:-INFO}" SOURCE_IP="local"
    SOURCE_IP=$(vps_tools_ssh_client_ip 2>/dev/null || printf 'local')
    mkdir -p "$(dirname "$VPS_AUDIT_LOG")" 2>/dev/null || true
    printf '%s\t%s\t%s\t%s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$RESULT" "$SOURCE_IP" "$ACTION" \
        2>/dev/null >> "$VPS_AUDIT_LOG" || true
    chmod 600 "$VPS_AUDIT_LOG" 2>/dev/null || true
}

archive_gzip_decompress_bounded() {
    local INPUT="$1" OUTPUT="$2" MAX_COMPRESSED="$3" MAX_RAW="$4"
    local COMPRESSED_SIZE RAW_SIZE
    [[ "$MAX_COMPRESSED" =~ ^[1-9][0-9]*$ ]] \
        && [[ "$MAX_RAW" =~ ^[1-9][0-9]*$ ]] || return 1
    COMPRESSED_SIZE=$(stat -c '%s' "$INPUT" 2>/dev/null) || return 1
    [[ "$COMPRESSED_SIZE" =~ ^[0-9]+$ ]] \
        && [ "$COMPRESSED_SIZE" -le "$MAX_COMPRESSED" ] || return 1
    if ! command -v gzip >/dev/null 2>&1 \
        || ! command -v head >/dev/null 2>&1 \
        || ! (set -o pipefail; gzip -dc < "$INPUT" 2>/dev/null \
            | head -c "$((MAX_RAW + 1))" > "$OUTPUT"); then
        rm -f "$OUTPUT"
        return 1
    fi
    RAW_SIZE=$(stat -c '%s' "$OUTPUT" 2>/dev/null) || {
        rm -f "$OUTPUT"
        return 1
    }
    [[ "$RAW_SIZE" =~ ^[0-9]+$ ]] && [ "$RAW_SIZE" -le "$MAX_RAW" ] || {
        rm -f "$OUTPUT"
        return 1
    }
}

# 兼容 dumb 终端（OpenWrt / tmux 等不支持 clear 的环境）
safe_clear() {
    if [ -n "${TERM:-}" ] && [ "$TERM" != "dumb" ]; then
        clear 2>/dev/null || true
    fi
}

systemd_available() {
    command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]
}

# 运行时探测 ssh.socket 是否是当前系统实际监听 SSH 连接的单元，
# 不按发行版/版本号猜测——不同 openssh-server 补丁版本行为并不一致
ssh_socket_activated() {
    systemd_available || return 1
    systemctl is-active --quiet ssh.socket 2>/dev/null
}

# 主菜单品牌字幅
volcano_art_banner() {
    ui_refresh_dimensions
    printf '%s' "${RED}${BOLD}"
    if [ "$BOX_W" -ge 76 ]; then
        cat << 'BANNER_WIDE_EOF'
██╗███╗   ███╗██████╗  █████╗ ██████╗ ████████╗     ██████╗ ██████╗ ███████╗
██║████╗ ████║██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝    ██╔═══██╗██╔══██╗██╔════╝
██║██╔████╔██║██████╔╝███████║██████╔╝   ██║       ██║   ██║██████╔╝███████╗
██║██║╚██╔╝██║██╔═══╝ ██╔══██║██╔══██╗   ██║       ██║   ██║██╔═══╝ ╚════██║
██║██║ ╚═╝ ██║██║     ██║  ██║██║  ██║   ██║       ╚██████╔╝██║     ███████║
╚═╝╚═╝     ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝        ╚═════╝ ╚═╝     ╚══════╝
BANNER_WIDE_EOF
    elif [ "$BOX_W" -ge 47 ]; then
        cat << 'BANNER_COMPACT_EOF'
██╗███╗   ███╗██████╗  █████╗ ██████╗ ████████╗
██║████╗ ████║██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝
██║██╔████╔██║██████╔╝███████║██████╔╝   ██║
██║██║╚██╔╝██║██╔═══╝ ██╔══██║██╔══██╗   ██║
██║██║ ╚═╝ ██║██║     ██║  ██║██║  ██║   ██║
╚═╝╚═╝     ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

            ██████╗ ██████╗ ███████╗
           ██╔═══██╗██╔══██╗██╔════╝
           ██║   ██║██████╔╝███████╗
           ██║   ██║██╔═══╝ ╚════██║
           ╚██████╔╝██║     ███████║
            ╚═════╝ ╚═╝     ╚══════╝
BANNER_COMPACT_EOF
    else
        local TITLE="IMPART OPS" PAD=$(( (BOX_W - 10) / 2 ))
        [ "$PAD" -lt 0 ] && PAD=0
        printf '%*s%s\n' "$PAD" '' "$TITLE"
    fi
    printf '%s' "${NC}"
}

# ── 可见宽度计算（用 python3，中文=2，ASCII=1）────────────
vis_len() {
    python3 -c "
import unicodedata, sys
s = sys.argv[1]
print(sum(2 if unicodedata.east_asian_width(c) in ('W','F') else 1 for c in s))
" "$1" 2>/dev/null || echo "${#1}"
}

# ── 响应式终端布局 ────────────────────────────────────────
BOX_W=64
UI_COMPACT=0
APP_UI_TITLE="VPS TOOLS"
APP_VERSION="V3.52.0"
APP_SUBTITLE="VPS 开荒脚本 · 银趴火山帮"

ui_refresh_dimensions() {
    local COLS="${COLUMNS:-}"
    if ! echo "$COLS" | grep -qE '^[0-9]+$'; then
        COLS=$(tput cols 2>/dev/null || echo 80)
    fi
    [ "$COLS" -gt 76 ] && COLS=76
    [ "$COLS" -lt 36 ] && COLS=36
    BOX_W=$COLS
    UI_COMPACT=0
    if [ "$BOX_W" -lt 66 ]; then UI_COMPACT=1; fi
}

ui_repeat() {
    local CHAR="$1" COUNT="$2" i
    for ((i=0; i<COUNT; i++)); do printf '%s' "$CHAR"; done
}

box_top() { ui_refresh_dimensions; printf '%s' "${BOLD}${CYAN}"; ui_repeat "━" "$BOX_W"; printf '%s\n' "$NC"; }
box_bot() { printf '%s' "${BOLD}${CYAN}"; ui_repeat "━" "$BOX_W"; printf '%s\n' "$NC"; }
box_sep() { printf '%s' "${DIM}${CYAN}"; ui_repeat "─" "$BOX_W"; printf '%s\n' "$NC"; }

# 居中标题行（只传纯文本，自动居中）
box_title() {
    local TEXT="$1"
    local LEN; LEN=$(vis_len "$TEXT")
    local INNER=$((BOX_W - 2))
    local PAD_TOTAL=$(( INNER - LEN ))
    [ "$PAD_TOTAL" -lt 0 ] && PAD_TOTAL=0
    local PAD_L=$(( PAD_TOTAL / 2 ))
    local PAD_R=$(( PAD_TOTAL - PAD_L ))
    printf '%*s' "$PAD_L" ''
    printf "${BOLD}${CYAN}%s${NC}" "$TEXT"
    printf '%*s' "$PAD_R" ''
    printf "\n"
}

# 普通内容行：PLAIN=纯文本(算宽度)  COLORED=带色码(显示用)
# 用法: box_line "纯文本" "带色码文本"
box_line() {
    local COLORED="${2:-$1}"
    echo -e "$COLORED"
}

# 空行
box_empty() {
    echo ""
}

# ── 内层分隔线（与主框线同宽对齐，dim 青，统一替代各处 seq 1 38）──
menu_div() { ui_refresh_dimensions; printf '%s' "${DIM}${CYAN}"; ui_repeat "─" "$BOX_W"; printf '%s\n' "$NC"; }

app_header_line() {
    echo -e "  ${DIM}${APP_UI_TITLE}  ·  ${APP_VERSION}${NC}"
}

app_subtitle_line() {
    echo -e "  ${BOLD}${CYAN}${APP_SUBTITLE}${NC}"
}

# ── 段标题（❯ 前缀，统一替代 [xxx] 方括号风格）──
menu_group() { echo -e "  ${CYAN}${BOLD}◆ ${1}${NC}"; }

# ── 菜单项（统一缩进与配色）。用法: menu_item "1" "SSH 工具集" [颜色]──
menu_item() {
    local KEY="$1" LABEL="$2" COL="${3:-$GREEN}"
    echo -e "    ${COL}${BOLD}${KEY}${NC}  ${LABEL}"
}

menu_pair() {
    local K1="$1" L1="$2" K2="${3:-}" L2="${4:-}" COL1="${5:-$GREEN}" COL2="${6:-$GREEN}"
    ui_refresh_dimensions
    if [ "$UI_COMPACT" = "1" ] || [ -z "$K2" ]; then
        menu_item "$K1" "$L1" "$COL1"
        [ -n "$K2" ] && menu_item "$K2" "$L2" "$COL2"
        return
    fi
    local LEFT="${K1}  ${L1}" TARGET=$((BOX_W / 2 - 3)) LEN PAD
    LEN=$(vis_len "$LEFT"); PAD=$((TARGET - LEN)); [ "$PAD" -lt 2 ] && PAD=2
    printf '    %s%s%s' "$COL1$BOLD" "$K1" "$NC"
    printf '  %s' "$L1"
    printf '%*s' "$PAD" ''
    printf '%s%s%s  %s\n' "$COL2$BOLD" "$K2" "$NC" "$L2"
}

status_dot() {
    local STATE="$1"
    case "$STATE" in
        active|running|yes|on|已启用|运行中) echo -e "${GREEN}●${NC}" ;;
        inactive|stopped|no|off|已停止) echo -e "${RED}●${NC}" ;;
        *) echo -e "${YELLOW}●${NC}" ;;
    esac
}

status_pair() {
    local L1="$1" V1="$2" S1="$3" L2="${4:-}" V2="${5:-}" S2="${6:-}" D1 D2 C1 C2
    case "$S1" in active|running|yes|on|已启用|运行中) C1="$GREEN" ;; inactive|stopped|no|off|已停止) C1="$RED" ;; *) C1="$YELLOW" ;; esac
    case "$S2" in active|running|yes|on|已启用|运行中) C2="$GREEN" ;; inactive|stopped|no|off|已停止) C2="$RED" ;; *) C2="$YELLOW" ;; esac
    D1="${C1}●${NC}"; D2="${C2}●${NC}"
    ui_refresh_dimensions
    if [ "$UI_COMPACT" = "1" ] || [ -z "$L2" ]; then
        echo -e "  $D1  ${DIM}${L1}${NC}  ${BOLD}${V1}${NC}"
        [ -n "$L2" ] && echo -e "  $D2  ${DIM}${L2}${NC}  ${BOLD}${V2}${NC}"
        return
    fi
    local PLAIN="●  ${L1}  ${V1}" TARGET=$((BOX_W / 2)) LEN PAD
    LEN=$(vis_len "$PLAIN"); PAD=$((TARGET - LEN)); [ "$PAD" -lt 2 ] && PAD=2
    echo -en "  $D1  ${DIM}${L1}${NC}  ${BOLD}${V1}${NC}"
    printf '%*s' "$PAD" ''
    echo -e "$D2  ${DIM}${L2}${NC}  ${BOLD}${V2}${NC}"
}

ui_hint() { echo -e "  ${DIM}› $1${NC}"; }
ui_prompt() { printf '  %s›%s %s' "$CYAN$BOLD" "$NC" "$1"; }
ui_pause() { echo ""; read -rp "$(ui_prompt '按 Enter 返回')" _; }
ui_continue() { echo ""; read -rp "$(ui_prompt '按 Enter 继续')" _; }


# ── 通用编辑器（兼容 Alpine/OpenWrt 等精简系统）────────────
get_editor() {
    for ed in nano vi vim; do
        command -v "$ed" &>/dev/null && echo "$ed" && return
    done
    echo "vi"  # 最后兜底，几乎所有系统都有 vi
}

open_editor() {
    local FILE="$1"
    local ED; ED=$(get_editor)
    if ! command -v "$ED" &>/dev/null; then
        # vi 也没有，尝试安装 nano
        warn "未找到编辑器，尝试安装 nano..."
        pkg_install nano &>/dev/null || pkg_install vim &>/dev/null || true
        ED=$(get_editor)
    fi
    "$ED" "$FILE"
}

# ── 确保 sysctl 可用（Alpine 需要 procps 或 sysctl 包）────
# 加载 nf_conntrack 模块（中转/落地机需要）
ensure_conntrack_module() {
    lsmod 2>/dev/null | grep -q "^nf_conntrack" && return 0
    modprobe nf_conntrack 2>/dev/null
}

ensure_sysctl() {
    command -v sysctl &>/dev/null && return 0
    warn "sysctl 未找到，正在安装..."
    if command -v apk &>/dev/null; then
        apk add --no-cache procps 2>/dev/null || apk add --no-cache sysctl 2>/dev/null || true
    else
        pkg_install procps 2>/dev/null || true
    fi
    command -v sysctl &>/dev/null && return 0
    error "sysctl 安装失败，请手动执行：apk add procps"
    return 1
}


# iptables/ip6tables 残留规则清理（卸载防火墙时使用）
clear_iptables_residue() {
    # 安全清理：只删除本脚本可能残留的规则，绝不 flush 全表、绝不改默认策略。
    # 旧版会 iptables -F + 设 ACCEPT，会瞬间裸奔并抹掉 NFT 转发/代理/用户自有规则。
    # ufw --force reset / firewalld 卸载本身已清掉各自规则，这里无需再 flush。
    local FAILED=no
    local NETFILTER_CMD CHECK_RC
    for NETFILTER_CMD in iptables ip6tables; do
        command -v "$NETFILTER_CMD" &>/dev/null || continue
        # 删除本脚本 SSH 放行可能残留的 INPUT ACCEPT 规则（逐条删，删到没有为止）
        local _p
        for _p in $(get_config "Port" 2>/dev/null) 22; do
            [ -n "$_p" ] || continue
            while true; do
                "$NETFILTER_CMD" -C INPUT -p tcp --dport "$_p" \
                    -j ACCEPT 2>/dev/null
                CHECK_RC=$?
                case "$CHECK_RC" in
                    0)
                        if ! "$NETFILTER_CMD" -D INPUT -p tcp \
                            --dport "$_p" -j ACCEPT 2>/dev/null; then
                            FAILED=yes
                            break
                        fi
                        ;;
                    1) break ;;
                    *) FAILED=yes; break ;;
                esac
            done
        done
    done
    if [ "$FAILED" = yes ]; then
        warn "本脚本的部分 iptables 残留规则未能删除"
        return 1
    fi
    info "已清理本脚本残留规则（未触碰默认策略与其它规则）"
}

# 统一标题栏
print_header() {
    safe_clear
    echo ""
    box_top
    app_header_line
    echo -e "  ${BOLD}${CYAN}$1${NC}"
    box_bot
    echo ""
}


# ── 兼容工具函数（支持 BusyBox / Alpine）─────────────────

# 替代 grep -oP '(?:maxrate|rate) \K\S+'
# 替代 grep -oE 'initcwnd [0-9]+' | awk '{print $2}'
# 检测服务管理器并重启 SSH
restart_ssh() {
    if systemd_available; then
        if ssh_socket_activated; then
            # socket 激活时，只重启 ssh.service 不会让新的 ListenStream 生效，
            # 必须先 daemon-reload 再重启 ssh.socket 本身
            systemctl daemon-reload 2>/dev/null
            systemctl restart ssh.socket 2>/dev/null || return 1
        fi
        systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service sshd restart 2>/dev/null || rc-service ssh restart 2>/dev/null
    elif command -v service &>/dev/null; then
        service ssh restart 2>/dev/null || service sshd restart 2>/dev/null
    else
        return 1
    fi
}

# 检测服务管理器并重启 fail2ban
restart_fail2ban() {
    if systemd_available; then
        systemctl restart fail2ban 2>/dev/null && return 0
    fi
    if command -v rc-service &>/dev/null; then
        rc-service fail2ban restart 2>/dev/null && return 0
    fi
    if command -v service &>/dev/null; then
        service fail2ban restart 2>/dev/null && return 0
    fi
    [ -x /etc/init.d/fail2ban ] && /etc/init.d/fail2ban restart 2>/dev/null
}

# 检测服务管理器并启动/停止 fail2ban
start_fail2ban() {
    # 确保 socket 目录存在（tmpfs 重启后会消失）
    mkdir -p /var/run/fail2ban 2>/dev/null
    chmod 755 /var/run/fail2ban 2>/dev/null

    # 写入 tmpfiles.d 确保重启后自动创建目录
    if command -v systemd-tmpfiles &>/dev/null; then
        echo "d /var/run/fail2ban 0755 root root -" > /etc/tmpfiles.d/fail2ban.conf 2>/dev/null
        systemd-tmpfiles --create /etc/tmpfiles.d/fail2ban.conf 2>/dev/null || true
    fi

    # 优先尝试 systemctl，失败则回退 service / rc-service
    if systemd_available; then
        systemctl start fail2ban 2>/dev/null && return 0
    fi
    if command -v rc-service &>/dev/null; then
        rc-service fail2ban start 2>/dev/null && return 0
    fi
    if command -v service &>/dev/null; then
        service fail2ban start 2>/dev/null && return 0
    fi
    # 最后回退：直接调用 init.d 脚本
    [ -x /etc/init.d/fail2ban ] && /etc/init.d/fail2ban start 2>/dev/null
}
stop_fail2ban() {
    if systemd_available; then
        systemctl stop fail2ban 2>/dev/null && return 0
    fi
    if command -v rc-service &>/dev/null; then
        rc-service fail2ban stop 2>/dev/null && return 0
    fi
    if command -v service &>/dev/null; then
        service fail2ban stop 2>/dev/null && return 0
    fi
    [ -x /etc/init.d/fail2ban ] && /etc/init.d/fail2ban stop 2>/dev/null
}

# ── 系统检测工具 ──────────────────────────────────────────

# 检测包管理器
pkg_install() {
    local PKG="$1"
    if command -v apt-get &>/dev/null; then
        apt-get update -qq 2>/dev/null
        apt-get install -y "$PKG" 2>/dev/null
    elif command -v apk &>/dev/null; then
        apk add --no-cache "$PKG" 2>/dev/null
    elif command -v yum &>/dev/null; then
        yum install -y "$PKG" 2>/dev/null
    elif command -v dnf &>/dev/null; then
        dnf install -y "$PKG" 2>/dev/null
    elif command -v pacman &>/dev/null; then
        pacman -Sy --noconfirm "$PKG" 2>/dev/null
    else
        return 1
    fi
}

pkg_remove() {
    local PKG="$1"
    if command -v apt-get &>/dev/null; then
        apt-get remove -y "$PKG" 2>/dev/null
    elif command -v apk &>/dev/null; then
        apk del "$PKG" 2>/dev/null
    elif command -v yum &>/dev/null; then
        yum remove -y "$PKG" 2>/dev/null
    elif command -v dnf &>/dev/null; then
        dnf remove -y "$PKG" 2>/dev/null
    else
        return 1
    fi
}

# 通用服务启用（开机自启）
svc_enable() {
    local SVC="$1"
    if systemd_available; then
        systemctl unmask "$SVC" 2>/dev/null || return 1
        systemctl enable "$SVC" --quiet 2>/dev/null
    elif command -v rc-update &>/dev/null; then
        rc-update add "$SVC" default 2>/dev/null
    elif command -v update-rc.d &>/dev/null; then
        update-rc.d "$SVC" enable 2>/dev/null
    else
        return 1
    fi
}

svc_disable() {
    local SVC="$1"
    if systemd_available; then
        systemctl disable "$SVC" --quiet 2>/dev/null
    elif command -v rc-update &>/dev/null; then
        rc-update del "$SVC" 2>/dev/null
    elif command -v update-rc.d &>/dev/null; then
        update-rc.d "$SVC" disable 2>/dev/null
    else
        return 1
    fi
}

# 通用服务 start/stop/restart 封装（systemd / OpenRC / sysvinit）
# OpenRC 服务名常带不同后缀，systemd 用 .service；调用方传裸名即可。
# 获取默认出口网卡：ip route get 比 awk '/^default/' 更准
# （多默认路由 / 策略路由 / IPv6-only 时不易取错），失败回退旧法
default_iface() {
    local DEV
    DEV=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')
    [ -z "$DEV" ] && DEV=$(ip -6 route get 2606:4700:4700::1111 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')
    [ -z "$DEV" ] && DEV=$(ip route 2>/dev/null | awk '/^default/{print $5; exit}')
    echo "$DEV"
}

svc_start() {
    local SVC="$1"
    if systemd_available; then
        systemctl start "$SVC" 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service "$SVC" start 2>/dev/null
    elif command -v service &>/dev/null; then
        service "$SVC" start 2>/dev/null
    else
        return 1
    fi
}

svc_stop() {
    local SVC="$1"
    if systemd_available; then
        systemctl stop "$SVC" 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service "$SVC" stop 2>/dev/null
    elif command -v service &>/dev/null; then
        service "$SVC" stop 2>/dev/null
    else
        return 1
    fi
}

svc_restart() {
    local SVC="$1"
    if systemd_available; then
        systemctl restart "$SVC" 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service "$SVC" restart 2>/dev/null
    elif command -v service &>/dev/null; then
        service "$SVC" restart 2>/dev/null
    else
        return 1
    fi
}

# 通用服务 is-active 检测
svc_is_active() {
    local SVC="$1"
    if systemd_available; then
        systemctl is-active --quiet "$SVC" 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service "$SVC" status &>/dev/null
    elif command -v service &>/dev/null; then
        service "$SVC" status &>/dev/null
    else
        return 1
    fi
}

# systemctl daemon-reload 兼容（OpenRC 不需要）
svc_daemon_reload() {
    command -v systemctl &>/dev/null && systemctl daemon-reload 2>/dev/null || true
}

# 获取 OS codename（兼容无 lsb_release 的系统）
get_codename() {
    if command -v lsb_release &>/dev/null; then
        lsb_release -cs 2>/dev/null
    elif [ -f /etc/os-release ]; then
        grep VERSION_CODENAME /etc/os-release | cut -d= -f2 | tr -d '"'
    elif [ -f /etc/debian_version ]; then
        cat /etc/debian_version | cut -d. -f1
    else
        echo "unknown"
    fi
}

# ── 权限检查与提权引导 ────────────────────────────────────
VPS_TOOLS_INSTALL_URL="https://raw.githubusercontent.com/TonyJsonson-8748/SSH-Hardening/refs/heads/main/SSH-Hardening.sh"

vps_tools_elevation_help() {
    local ELEVATOR="${1:-sudo}"
    echo ""
    echo "本脚本会修改系统用户、SSH、防火墙和服务配置，必须使用 root 权限。"
    if [ "$ELEVATOR" = "doas" ]; then
        echo "通过网络运行：doas bash -c 'bash <(curl -fsSL $VPS_TOOLS_INSTALL_URL)'"
        echo "已安装后运行：doas v"
    else
        echo "通过网络运行：sudo bash -c 'bash <(curl -fsSL $VPS_TOOLS_INSTALL_URL)'"
        echo "已安装后运行：sudo v"
    fi
    echo "没有 sudo/doas 时：先执行 su - 切换到 root，再重新运行。"
}

vps_tools_require_root_or_elevate() {
    local ELEVATOR="" ANSWER="" CURRENT_USER SSH_CONTEXT="" SSH_FAMILY=""
    [ "$EUID" -eq 0 ] && return 0
    CURRENT_USER=$(id -un 2>/dev/null || echo "UID $EUID")
    echo -e "${RED}[ERROR]${NC} 当前用户 ${CURRENT_USER} 不是 root。"

    if command -v sudo >/dev/null 2>&1; then
        ELEVATOR=sudo
    elif command -v doas >/dev/null 2>&1; then
        ELEVATOR=doas
    fi

    case "$0" in
        /dev/fd/*|/proc/*/fd/*)
            vps_tools_elevation_help "${ELEVATOR:-sudo}"
            echo "当前使用 bash <(curl ...) 运行，文件描述符不能安全传给提权进程，请复制上面的命令重试。"
            return 1
            ;;
    esac

    if [ -z "$ELEVATOR" ]; then
        vps_tools_elevation_help sudo
        echo "当前系统未检测到 sudo 或 doas，请联系管理员授予权限。"
        return 1
    fi
    if [ ! -t 0 ]; then
        vps_tools_elevation_help "$ELEVATOR"
        echo "当前不是交互终端，无法安全询问提权密码。"
        return 1
    fi

    read -rp "  是否使用 ${ELEVATOR} 以 root 权限重新运行？(Y/n): " ANSWER
    [ -z "$ANSWER" ] && ANSWER=y
    echo "$ANSWER" | grep -qiE '^y(es)?$' || {
        vps_tools_elevation_help "$ELEVATOR"
        return 1
    }

    SSH_CONTEXT=$(vps_tools_ssh_connection 2>/dev/null || true)
    SSH_FAMILY=$(vps_tools_ssh_family 2>/dev/null || true)
    if [ "$ELEVATOR" = sudo ]; then
        if sudo -v; then
            exec sudo env \
                VPS_TOOLS_SSH_CONNECTION="$SSH_CONTEXT" \
                VPS_TOOLS_SSH_FAMILY="$SSH_FAMILY" \
                bash "$0" "$@"
        fi
    elif doas true; then
        exec doas env \
            VPS_TOOLS_SSH_CONNECTION="$SSH_CONTEXT" \
            VPS_TOOLS_SSH_FAMILY="$SSH_FAMILY" \
            bash "$0" "$@"
    fi
    echo -e "${RED}[ERROR]${NC} ${ELEVATOR} 提权失败，当前账号可能没有管理员权限。"
    vps_tools_elevation_help "$ELEVATOR"
    return 1
}

if [ "$EUID" -ne 0 ] && [ "${VPS_TOOLS_TEST_MODE:-0}" != "1" ] && [ "${1:-}" != "--help" ] && [ "${1:-}" != "-h" ] && [ "${1:-}" != "help" ]; then
    vps_tools_require_root_or_elevate "$@" || exit 1
fi

# ── 通用工具函数 ──────────────────────────────────────────
sshd_effective_value() {
    local KEY="$1" WANT VALUE
    command -v sshd >/dev/null 2>&1 || return 1
    WANT=$(printf '%s' "$KEY" | tr '[:upper:]' '[:lower:]')
    VALUE=$(sshd -T 2>/dev/null | awk -v k="$WANT" \
        'tolower($1) == tolower(k) {print $2; exit}')
    [ -n "$VALUE" ] || return 1
    printf '%s\n' "$VALUE"
}

get_config() {
    local VALUE
    VALUE=$(sshd_effective_value "$1" 2>/dev/null || true)
    [ -n "$VALUE" ] && { printf '%s\n' "$VALUE"; return 0; }
    awk -v key="$1" '
        tolower($1) == tolower(key) {value=$2}
        END {if (value != "") print value}
    ' "$SSHD_CONFIG" 2>/dev/null
}

ssh_key_count() {
    local COUNT
    COUNT=$(grep -cE '^(ssh-rsa|ssh-ed25519|ecdsa-sha2|sk-ssh|sk-ecdsa|ssh-dss) ' "$AUTH_KEYS" 2>/dev/null || true)
    case "$COUNT" in
        ''|*[!0-9]*) printf '0\n' ;;
        *) printf '%s\n' "$COUNT" ;;
    esac
}

set_config_file() {
    local FILE="$1" KEY="$2" VALUE="$3"
    local BODY="" BLOCK="" TMP="" KEY_LOWER
    if [ -e "$FILE" ] || [ -L "$FILE" ]; then
        [ -f "$FILE" ] && [ ! -L "$FILE" ] || return 1
    else
        : > "$FILE" || return 1
    fi
    BODY=$(mktemp) || return 1
    BLOCK=$(mktemp) || { rm -f "$BODY"; return 1; }
    TMP=$(mktemp "${FILE}.vps-tools.XXXXXX") || {
        rm -f "$BODY" "$BLOCK"
        return 1
    }
    if ! cp -a -- "$FILE" "$TMP"; then
        rm -f "$BODY" "$BLOCK" "$TMP"
        return 1
    fi
    KEY_LOWER=$(printf '%s' "$KEY" | tr '[:upper:]' '[:lower:]') || {
        rm -f "$BODY" "$BLOCK" "$TMP"
        return 1
    }

    if ! awk -v begin="$SSHD_MANAGED_BEGIN" -v end="$SSHD_MANAGED_END" \
        -v key_lower="$KEY_LOWER" '
        function first_field(line, fields) {
            sub(/^[[:space:]]+/, "", line)
            split(line, fields, /[[:space:]]+/)
            return tolower(fields[1])
        }
        $0 == begin {in_block=1; next}
        $0 == end {in_block=0; next}
        in_block {next}
        {
            field=first_field($0)
            if (field == "match") in_match=1
            # Port is additive in sshd_config. Remove active, unmanaged,
            # global Port directives so changing the managed value cannot
            # silently leave the old listener enabled.
            if (key_lower == "port" && !in_match && field == "port") next
            print
        }
    ' "$FILE" > "$BODY"; then
        rm -f "$BODY" "$BLOCK" "$TMP"
        return 1
    fi

    if ! awk -v begin="$SSHD_MANAGED_BEGIN" -v end="$SSHD_MANAGED_END" -v key="$KEY" '
        $0 == begin {in_block=1; next}
        $0 == end {in_block=0; next}
        in_block {
            line=$0
            sub(/^[[:space:]]+/, "", line)
            split(line, fields, /[[:space:]]+/)
            if (line != "" && tolower(fields[1]) != tolower(key)) print line
        }
    ' "$FILE" > "$BLOCK"; then
        rm -f "$BODY" "$BLOCK" "$TMP"
        return 1
    fi

    if ! {
        printf '%s\n' "$SSHD_MANAGED_BEGIN" \
            && cat "$BLOCK" \
            && printf '%s\n' "${KEY} ${VALUE}" \
            && printf '%s\n\n' "$SSHD_MANAGED_END" \
            && cat "$BODY"
    } > "$TMP"; then
        rm -f "$BODY" "$BLOCK" "$TMP"
        return 1
    fi
    if ! mv -f -- "$TMP" "$FILE"; then
        rm -f "$BODY" "$BLOCK" "$TMP"
        return 1
    fi
    rm -f "$BODY" "$BLOCK" || true
    return 0
}

set_config() {
    set_config_file "$SSHD_CONFIG" "$1" "$2"
}

backup_config() {
    local BACKUP CURRENT_STATE BACKUP_DIGEST BACKUP_STATE
    [ -f "$SSHD_CONFIG" ] && [ ! -L "$SSHD_CONFIG" ] || {
        error "SSH 配置必须是普通文件，拒绝修改符号链接或特殊文件：$SSHD_CONFIG"
        return 1
    }
    if command -v ssh_config_file_state >/dev/null 2>&1; then
        CURRENT_STATE=$(ssh_config_file_state "$SSHD_CONFIG") || {
            error "无法稳定读取 SSH 配置，拒绝创建可能不一致的备份"
            return 1
        }
        if [ -n "${SSH_CONFIG_PREPARED_STATE:-}" ] \
            && [ "$CURRENT_STATE" != "$SSH_CONFIG_PREPARED_STATE" ]; then
            error "候选配置准备后 sshd_config 已发生变化，请重新操作"
            return 1
        fi
    fi
    BACKUP="$SSHD_CONFIG.bak.$(date +%Y%m%d_%H%M%S)_$$_${RANDOM}"
    if ! cp -a -- "$SSHD_CONFIG" "$BACKUP" \
        || ! cmp -s "$SSHD_CONFIG" "$BACKUP"; then
        rm -f "$BACKUP"
        error "无法备份 SSH 配置：$SSHD_CONFIG"
        return 1
    fi
    BACKUP_DIGEST=$(cksum < "$BACKUP" 2>/dev/null) || {
        rm -f -- "$BACKUP"
        error "无法校验 SSH 配置备份"
        return 1
    }
    if command -v ssh_config_file_state >/dev/null 2>&1; then
        BACKUP_STATE=$(ssh_config_file_state "$BACKUP") || {
            rm -f -- "$BACKUP"
            error "无法稳定记录 SSH 配置备份状态"
            return 1
        }
    fi
    LAST_SSHD_BACKUP="$BACKUP"   # 供 apply_and_restart 失败时回滚
    LAST_SSHD_BACKUP_DIGEST="$BACKUP_DIGEST"
    LAST_SSHD_BACKUP_STATE="$BACKUP_STATE"
    if command -v ssh_socket_override_backup >/dev/null 2>&1 \
        && ! ssh_socket_override_backup; then
        rm -f -- "$BACKUP"
        error "无法备份 SSH socket 端口覆盖文件：$SSHD_SOCKET_OVERRIDE_FILE"
        return 1
    fi
    info "配置已备份：$BACKUP"
}

ssh_config_file_restore_state() {
    local FILE="$1" BEFORE_META AFTER_META DIGEST
    [ -f "$FILE" ] && [ ! -L "$FILE" ] || return 1
    BEFORE_META=$(stat -Lc '%u:%g:%a:%s:%Y:%F' -- "$FILE" 2>/dev/null) \
        || return 1
    DIGEST=$(cksum < "$FILE" 2>/dev/null) || return 1
    AFTER_META=$(stat -Lc '%u:%g:%a:%s:%Y:%F' -- "$FILE" 2>/dev/null) \
        || return 1
    [ "$AFTER_META" = "$BEFORE_META" ] || return 1
    printf '%s|%s\n' "$BEFORE_META" "$DIGEST"
}

# shellcheck disable=SC2120  # BACKUP falls back to LAST_SSHD_BACKUP; kept callable with an explicit path
restore_ssh_config_backup() {
    local BACKUP="${1:-${LAST_SSHD_BACKUP:-}}" RESTORE_TMP=""
    local BACKUP_DIGEST CURRENT_DIGEST CURRENT_STATE SECOND_STATE
    local BACKUP_STATE CURRENT_RESTORE_STATE BACKUP_RESTORE_STATE NEEDS_RESTORE=no
    [ -n "$BACKUP" ] && [ -f "$BACKUP" ] && [ ! -L "$BACKUP" ] || {
        error "未找到可回滚的 SSH 配置备份"
        return 1
    }
    [ -f "$SSHD_CONFIG" ] && [ ! -L "$SSHD_CONFIG" ] || {
        error "SSH 配置目标不再是安全的普通文件，拒绝覆盖：$SSHD_CONFIG"
        return 1
    }
    BACKUP_DIGEST=$(cksum < "$BACKUP" 2>/dev/null) || return 1
    if [ "$BACKUP" = "${LAST_SSHD_BACKUP:-}" ]; then
        if [ -z "${LAST_SSHD_BACKUP_DIGEST:-}" ] \
            || [ "$BACKUP_DIGEST" != "$LAST_SSHD_BACKUP_DIGEST" ]; then
            error "SSH 配置备份内容已在创建后发生变化，拒绝用于回滚"
            return 1
        fi
        if [ -n "${LAST_SSHD_BACKUP_STATE:-}" ] \
            && command -v ssh_config_file_state >/dev/null 2>&1; then
            BACKUP_STATE=$(ssh_config_file_state "$BACKUP") || return 1
            if [ "$BACKUP_STATE" != "$LAST_SSHD_BACKUP_STATE" ]; then
                error "SSH 配置备份元数据已在创建后发生变化，拒绝用于回滚"
                return 1
            fi
        fi
    fi
    CURRENT_DIGEST=$(cksum < "$SSHD_CONFIG" 2>/dev/null) || return 1
    BACKUP_RESTORE_STATE=$(ssh_config_file_restore_state "$BACKUP") || return 1
    CURRENT_RESTORE_STATE=$(ssh_config_file_restore_state "$SSHD_CONFIG") || return 1
    [ "$CURRENT_RESTORE_STATE" = "$BACKUP_RESTORE_STATE" ] || NEEDS_RESTORE=yes
    if [ "$NEEDS_RESTORE" = yes ]; then
        if command -v ssh_config_file_state >/dev/null 2>&1; then
            CURRENT_STATE=$(ssh_config_file_state "$SSHD_CONFIG") || return 1
            if [ -z "${SSH_CONFIG_APPLIED_DIGEST:-}" ] \
                || [ -z "${SSH_CONFIG_APPLIED_STATE:-}" ] \
                || [ "$CURRENT_DIGEST" != "$SSH_CONFIG_APPLIED_DIGEST" ] \
                || [ "$CURRENT_STATE" != "$SSH_CONFIG_APPLIED_STATE" ]; then
                error "sshd_config 在回滚前出现并发修改，拒绝用旧备份覆盖"
                return 1
            fi
        fi
        RESTORE_TMP=$(mktemp "${SSHD_CONFIG}.vps-tools-restore.XXXXXX") || return 1
        if ! cp -a -- "$BACKUP" "$RESTORE_TMP" \
            || ! cmp -s "$BACKUP" "$RESTORE_TMP"; then
            rm -f -- "$RESTORE_TMP"
            error "无法准备原子 SSH 配置恢复文件：$BACKUP"
            return 1
        fi
        if command -v ssh_config_file_state >/dev/null 2>&1; then
            SECOND_STATE=$(ssh_config_file_state "$SSHD_CONFIG") || SECOND_STATE=""
            if [ "$SECOND_STATE" != "$CURRENT_STATE" ]; then
                rm -f -- "$RESTORE_TMP"
                error "SSH 配置在恢复提交前再次发生变化，拒绝覆盖"
                return 1
            fi
        fi
        if ! mv -f -- "$RESTORE_TMP" "$SSHD_CONFIG" 2>/dev/null; then
            rm -f -- "$RESTORE_TMP"
            error "无法原子恢复 sshd_config，请立即手动处理：$BACKUP"
            return 1
        fi
    fi
    CURRENT_RESTORE_STATE=$(ssh_config_file_restore_state "$SSHD_CONFIG") || return 1
    if [ "$CURRENT_RESTORE_STATE" != "$BACKUP_RESTORE_STATE" ]; then
        error "无法从备份恢复 sshd_config，请立即手动处理：$BACKUP"
        return 1
    fi
    warn "已回滚 sshd_config 到备份：$BACKUP"
    if command -v ssh_socket_override_restore >/dev/null 2>&1 \
        && ! ssh_socket_override_restore; then
        error "无法回滚 SSH socket 端口覆盖文件，请立即手动检查：$SSHD_SOCKET_OVERRIDE_FILE"
        return 1
    fi
    if sshd -t 2>/dev/null && restart_ssh; then
        info "已用备份配置恢复 SSH 服务 ✓"
        return 0
    fi
    error "配置已恢复，但 SSH 服务仍异常，请立即手动检查！"
    return 1
}

apply_and_restart() {
    if ! sshd -t 2>/dev/null; then
        error "配置文件语法错误，自动回滚中..."
        restore_ssh_config_backup && return 1
        return 2
    fi
    if restart_ssh; then
        info "SSH 服务已重启 ✓"
    else
        error "SSH 服务重启失败，自动回滚中..."
        restore_ssh_config_backup && return 1
        return 2
    fi
}

list_keys() {
    if [ ! -f "$AUTH_KEYS" ] || ! grep -qE '^(ssh-rsa|ssh-ed25519|ecdsa-sha2|sk-ssh|sk-ecdsa|ssh-dss) ' "$AUTH_KEYS" 2>/dev/null; then
        echo -e "  ${YELLOW}（暂无公钥）${NC}"
        return 1
    fi
    local i=1
    while IFS= read -r line; do
        if echo "$line" | grep -qE '^(ssh-rsa|ssh-ed25519|ecdsa-sha2|sk-ssh|sk-ecdsa|ssh-dss) '; then
            local TYPE COMMENT FINGER
            TYPE=$(echo "$line" | awk '{print $1}')
            COMMENT=$(echo "$line" | awk '{print $3}')
            FINGER=$(echo "$line" | ssh-keygen -lf /dev/stdin 2>/dev/null | awk '{print $2}' || echo "N/A")
            echo -e "  ${GREEN}[$i]${NC} ${BOLD}$TYPE${NC}"
            echo -e "      ${DIM}指纹：${NC}${BLUE}$FINGER${NC}"
            echo -e "      ${DIM}备注：${NC}${YELLOW}${COMMENT:-（无备注）}${NC}"
            echo ""
            i=$((i+1))
        fi
    done < "$AUTH_KEYS"
    return 0
}

firewall_iptables_persistence_available() {
    local RULES_FILE="$1"
    [ "${VPS_TOOLS_TEST_MODE:-0}" = 1 ] && return 0
    case "$RULES_FILE" in
        /etc/iptables/rules.v4|/etc/iptables/rules.v6) ;;
        *) return 1 ;;
    esac
    command -v systemctl >/dev/null 2>&1 || return 1
    systemctl is-enabled --quiet netfilter-persistent.service >/dev/null 2>&1
}

firewall_iptables_save_rules() {
    local RULES_FILE="$1" SAVE_TMP SAVE_COMMAND=""
    case "$RULES_FILE" in
        *.v6) SAVE_COMMAND=ip6tables-save ;;
        *.v4) SAVE_COMMAND=iptables-save ;;
        *) SAVE_COMMAND="${FIREWALL_NETFILTER_SAVE_CMD:-iptables-save}" ;;
    esac
    command -v "$SAVE_COMMAND" >/dev/null 2>&1 || return 1
    firewall_iptables_persistence_available "$RULES_FILE" || return 1
    [ -f "$RULES_FILE" ] && [ ! -L "$RULES_FILE" ] || return 1
    SAVE_TMP=$(mktemp "${RULES_FILE}.vps-tools.XXXXXX") || return 1
    if ! cp -a -- "$RULES_FILE" "$SAVE_TMP" \
        || ! "$SAVE_COMMAND" > "$SAVE_TMP" \
        || ! mv -f -- "$SAVE_TMP" "$RULES_FILE"; then
        rm -f -- "$SAVE_TMP"
        return 1
    fi
}

firewall_ufw_port_state() {
    local STATUS="$1" PORT="$2"
    printf '%s\n' "$STATUS" | LC_ALL=C awk -v port="${PORT}/tcp" '
        {
            port_index=0
            for (i=1; i<=NF; i++) if ($i == port) {port_index=i; break}
            if (!port_index) next
            action=""
            action_index=0
            scoped=(port_index > 1)
            for (i=port_index+1; i<=NF; i++) {
                if ($i == "on") scoped=1
                if ($i == "ALLOW" || $i == "DENY" || $i == "REJECT" \
                    || $i == "LIMIT") {
                    action=$i
                    action_index=i
                    break
                }
            }
            if (!action_index) next
            direction=""
            source_index=action_index + 1
            if ($(source_index) == "IN" || $(source_index) == "OUT" \
                || $(source_index) == "FWD") {
                direction=$(source_index)
                source_index++
            }
            source=$(source_index)
            inbound=(direction == "" || direction == "IN")
            if (inbound && (action == "DENY" || action == "REJECT")) denied=1
            if (inbound && (action == "ALLOW" || action == "LIMIT") \
                && (scoped || source != "Anywhere")) policy=1
            if (inbound && !scoped && action == "ALLOW" \
                && source == "Anywhere") allowed=1
            if (inbound && !scoped && action == "LIMIT" \
                && source == "Anywhere") limited=1
        }
        END {
            if (denied) print "deny"
            else if (policy) print "policy"
            else if (allowed && limited) print "allow-limit"
            else if (allowed) print "allow"
            else if (limited) print "limit"
            else print "missing"
        }
    '
}

firewall_ufw_allow_count() {
    local STATUS="$1" PORT="$2"
    printf '%s\n' "$STATUS" | LC_ALL=C awk -v port="${PORT}/tcp" '
        {
            port_index=0
            for (i=1; i<=NF; i++) if ($i == port) {port_index=i; break}
            if (!port_index) next
            action=""
            action_index=0
            scoped=0
            for (i=port_index+1; i<=NF; i++) {
                if ($i == "on") scoped=1
                if ($i == "ALLOW" || $i == "LIMIT") {
                    action=$i
                    action_index=i
                    break
                }
                if ($i == "DENY" || $i == "REJECT") break
            }
            if (!action_index) next
            direction=""
            source_index=action_index + 1
            if ($(source_index) == "IN" || $(source_index) == "OUT" \
                || $(source_index) == "FWD") {
                direction=$(source_index)
                source_index++
            }
            if ((direction == "" || direction == "IN") && !scoped \
                && (action == "ALLOW" || action == "LIMIT") \
                && $(source_index) == "Anywhere") count++
        }
        END {print count+0}
    '
}

firewall_firewalld_ssh_zone() {
    local CLIENT_IP="" ROUTE="" IFACE="" ZONE="" ACTIVE_ZONES=""
    local SOURCE_ZONE="" PERMANENT_SOURCE_ZONE=""
    if [ -n "${FIREWALL_TEST_ZONE:-}" ] && [ "${VPS_TOOLS_TEST_MODE:-0}" = 1 ]; then
        printf '%s\n' "$FIREWALL_TEST_ZONE"
        return 0
    fi
    ACTIVE_ZONES=$(LC_ALL=C firewall-cmd --get-active-zones 2>/dev/null) || return 1
    CLIENT_IP=$(vps_tools_ssh_client_ip 2>/dev/null || true)
    if [ -n "$CLIENT_IP" ]; then
        if SOURCE_ZONE=$(LC_ALL=C firewall-cmd \
            --get-zone-of-source="$CLIENT_IP" 2>/dev/null); then
            case "$SOURCE_ZONE" in ""|"no zone") SOURCE_ZONE="" ;; esac
        else
            SOURCE_ZONE=""
        fi
        if PERMANENT_SOURCE_ZONE=$(LC_ALL=C firewall-cmd --permanent \
            --get-zone-of-source="$CLIENT_IP" 2>/dev/null); then
            case "$PERMANENT_SOURCE_ZONE" in
                ""|"no zone") PERMANENT_SOURCE_ZONE="" ;;
            esac
        else
            PERMANENT_SOURCE_ZONE=""
        fi
        if [ -n "$SOURCE_ZONE" ]; then
            [[ "$SOURCE_ZONE" =~ ^[A-Za-z0-9_-]+$ ]] || return 1
            [ "$PERMANENT_SOURCE_ZONE" = "$SOURCE_ZONE" ] || return 1
            printf '%s\n' "$SOURCE_ZONE"
            return 0
        fi
        # A permanent-only source binding means the runtime and next reload
        # would route this client through different zones.
        [ -z "$PERMANENT_SOURCE_ZONE" ] || return 1
        if printf '%s\n' "$ACTIVE_ZONES" \
            | grep -q '^[[:space:]]*sources:[[:space:]]'; then
            return 1
        fi
    fi
    if [ -n "$CLIENT_IP" ] && command -v ip >/dev/null 2>&1; then
        ROUTE=$(LC_ALL=C ip route get "$CLIENT_IP" 2>/dev/null) || return 1
        IFACE=$(printf '%s\n' "$ROUTE" | awk '
            {
                for (i=1; i<NF; i++) if ($i == "dev") {print $(i+1); exit}
            }
        ')
    fi
    if [ -n "$IFACE" ]; then
        ZONE=$(LC_ALL=C firewall-cmd --get-zone-of-interface="$IFACE" 2>/dev/null) \
            || return 1
        case "$ZONE" in
            ""|"no zone")
                ZONE=$(LC_ALL=C firewall-cmd --get-default-zone 2>/dev/null) || return 1
                ;;
        esac
    else
        ZONE=$(printf '%s\n' "$ACTIVE_ZONES" \
            | awk '/^[^[:space:]]/ {zone=$1; count++} END {if (count == 1) print zone}')
    fi
    [[ "$ZONE" =~ ^[A-Za-z0-9_-]+$ ]] || return 1
    printf '%s\n' "$ZONE"
}

firewall_detect_backend() {
    local FIREWALLD_STATE="" NFT_RULESET="" CLIENT_ADDR="" CLIENT_FAMILY=""
    local NFT_NATIVE_ACTIVE=no
    FIREWALL_BACKEND=none
    FIREWALL_UFW_STATUS=""
    FIREWALL_IPTABLES_V4_RULES=""
    FIREWALL_IPTABLES_V6_RULES=""
    FIREWALL_IPTABLES_V4_ACTIVE=no
    FIREWALL_IPTABLES_V6_ACTIVE=no
    FIREWALL_FIREWALLD_ZONE=""
    FIREWALL_NETFILTER_CMD=iptables
    FIREWALL_NETFILTER_SAVE_CMD=iptables-save
    FIREWALL_NETFILTER_RULES_DEFAULT=/etc/iptables/rules.v4
    CLIENT_ADDR=$(vps_tools_ssh_client_ip 2>/dev/null || true)
    CLIENT_FAMILY=$(vps_tools_ssh_family 2>/dev/null || true)
    if [ "$CLIENT_FAMILY" = 6 ]; then
        FIREWALL_NETFILTER_CMD=ip6tables
        FIREWALL_NETFILTER_SAVE_CMD=ip6tables-save
        FIREWALL_NETFILTER_RULES_DEFAULT=/etc/iptables/rules.v6
    fi

    if command -v ufw >/dev/null 2>&1; then
        FIREWALL_UFW_STATUS=$(LC_ALL=C ufw status 2>/dev/null) || {
            error "无法可靠读取 UFW 状态，拒绝继续修改 SSH 端口"
            return 1
        }
        case "$FIREWALL_UFW_STATUS" in
            *"Status: active"*)
                FIREWALL_BACKEND=ufw
                return 0
                ;;
            *"Status: inactive"*) ;;
            *)
                error "UFW 返回未知状态，拒绝继续修改 SSH 端口"
                return 1
                ;;
        esac
    fi

    if command -v firewall-cmd >/dev/null 2>&1; then
        if svc_is_active firewalld; then
            FIREWALLD_STATE=active
        elif command -v systemctl >/dev/null 2>&1; then
            FIREWALLD_STATE=$(LC_ALL=C systemctl is-active firewalld.service 2>/dev/null) \
                || true
            case "$FIREWALLD_STATE" in
                inactive|failed|unknown) FIREWALLD_STATE=inactive ;;
                active) ;;
                *)
                    error "无法可靠读取 firewalld 状态，拒绝继续修改 SSH 端口"
                    return 1
                    ;;
            esac
        elif LC_ALL=C firewall-cmd --state >/dev/null 2>&1; then
            FIREWALLD_STATE=active
        else
            error "无法可靠确认 firewalld 是否活跃，拒绝继续修改 SSH 端口"
            return 1
        fi
        if [ "$FIREWALLD_STATE" = active ]; then
            FIREWALL_FIREWALLD_ZONE=$(firewall_firewalld_ssh_zone) || {
                error "无法定位 SSH 入站接口对应的 firewalld zone，拒绝修改错误的 zone"
                return 1
            }
            FIREWALL_BACKEND=firewalld
            return 0
        fi
    fi

    if command -v iptables >/dev/null 2>&1; then
        FIREWALL_IPTABLES_V4_RULES=$(iptables -S INPUT 2>/dev/null) || {
            error "无法可靠读取 iptables INPUT 状态，拒绝继续修改 SSH 端口"
            return 1
        }
        if printf '%s\n' "$FIREWALL_IPTABLES_V4_RULES" | awk '
            $1 == "-P" && $2 == "INPUT" && $3 != "ACCEPT" {active=1}
            $1 == "-A" && $2 == "INPUT" {active=1}
            END {exit !active}
        '; then
            FIREWALL_IPTABLES_V4_ACTIVE=yes
        fi
    fi
    if command -v ip6tables >/dev/null 2>&1; then
        FIREWALL_IPTABLES_V6_RULES=$(ip6tables -S INPUT 2>/dev/null) || {
            error "无法可靠读取 ip6tables INPUT 状态，拒绝继续修改 SSH 端口"
            return 1
        }
        if printf '%s\n' "$FIREWALL_IPTABLES_V6_RULES" | awk '
            $1 == "-P" && $2 == "INPUT" && $3 != "ACCEPT" {active=1}
            $1 == "-A" && $2 == "INPUT" {active=1}
            END {exit !active}
        '; then
            FIREWALL_IPTABLES_V6_ACTIVE=yes
        fi
    fi
    if command -v nft >/dev/null 2>&1; then
        NFT_RULESET=$(LC_ALL=C nft list ruleset 2>/dev/null) || {
            error "无法可靠读取原生 nftables 状态，拒绝继续修改 SSH 端口"
            return 1
        }
        if printf '%s\n' "$NFT_RULESET" | awk \
            -v iptables_v4="$FIREWALL_IPTABLES_V4_ACTIVE" \
            -v iptables_v6="$FIREWALL_IPTABLES_V6_ACTIVE" '
            function chain_is_independent() {
                if (table_family == "inet") return 1
                if (table_family == "ip" && iptables_v4 == "yes" \
                    && table_name == "filter" && chain_name == "INPUT") return 0
                if (table_family == "ip6" && iptables_v6 == "yes" \
                    && table_name == "filter" && chain_name == "INPUT") return 0
                return table_family == "ip" || table_family == "ip6"
            }
            {
                line=$0
                if ($1 == "table") {
                    table_family=$2
                    table_name=$3
                    gsub(/[{};]/, "", table_name)
                }
                if ($1 == "chain") {
                    in_chain=1
                    chain_base_depth=depth
                    chain_name=$2
                    gsub(/[{};]/, "", chain_name)
                    has_input_hook=0
                }
                if (in_chain) {
                    if (line ~ /hook[[:space:]]+input/) has_input_hook=1
                }
                brace_line=line
                opens=gsub(/{/, "{", brace_line)
                brace_line=line
                closes=gsub(/}/, "}", brace_line)
                depth += opens - closes
                if (in_chain && depth <= chain_base_depth) {
                    if (has_input_hook && chain_is_independent()) found=1
                    in_chain=0
                }
            }
            END {exit !found}
        '; then
            NFT_NATIVE_ACTIVE=yes
        fi
    fi
    if { [ "$FIREWALL_IPTABLES_V4_ACTIVE" = yes ] \
            || [ "$FIREWALL_IPTABLES_V6_ACTIVE" = yes ]; } \
        && [ "$NFT_NATIVE_ACTIVE" = yes ]; then
        error "检测到 iptables 与独立 nftables INPUT 规则同时生效，无法安全选择唯一防火墙后端"
        return 1
    fi
    if [ "$FIREWALL_IPTABLES_V4_ACTIVE" = yes ] \
        || [ "$FIREWALL_IPTABLES_V6_ACTIVE" = yes ]; then
        FIREWALL_BACKEND=iptables
    elif [ "$NFT_NATIVE_ACTIVE" = yes ]; then
        FIREWALL_BACKEND=nft-unsupported
    fi
    return 0
}

firewall_rollback_allowed_port() {
    local PORT="$1" FAILED=no
    local NETFILTER_CMD="${FIREWALL_ALLOW_NETFILTER_CMD:-iptables}"
    FIREWALL_ALLOW_DIRTY=yes

    if [ "${FIREWALL_ALLOW_UFW_ADDED:-no}" = yes ]; then
        if ufw delete allow "${PORT}/tcp" >/dev/null 2>&1; then
            FIREWALL_ALLOW_UFW_ADDED=no
        else
            FAILED=yes
            warn "回滚本次新增的 ufw ${PORT}/tcp 规则失败"
        fi
    fi
    if [ "${FIREWALL_ALLOW_FIREWALLD_RUNTIME_ADDED:-no}" = yes ]; then
        if firewall-cmd --zone="${FIREWALL_ALLOW_FIREWALLD_ZONE}" \
            --remove-port="${PORT}/tcp" >/dev/null 2>&1; then
            FIREWALL_ALLOW_FIREWALLD_RUNTIME_ADDED=no
        else
            FAILED=yes
            warn "回滚本次新增的 firewalld 运行时 ${PORT}/tcp 规则失败"
        fi
    fi
    if [ "${FIREWALL_ALLOW_FIREWALLD_PERMANENT_ADDED:-no}" = yes ]; then
        if firewall-cmd --permanent --zone="${FIREWALL_ALLOW_FIREWALLD_ZONE}" \
            --remove-port="${PORT}/tcp" >/dev/null 2>&1; then
            FIREWALL_ALLOW_FIREWALLD_PERMANENT_ADDED=no
        else
            FAILED=yes
            warn "回滚本次新增的 firewalld 永久 ${PORT}/tcp 规则失败"
        fi
    fi
    if [ "${FIREWALL_ALLOW_IPTABLES_V4_ADDED:-no}" = yes ]; then
        if iptables -D INPUT -p tcp --dport "$PORT" -j ACCEPT \
            >/dev/null 2>&1; then
            if firewall_iptables_save_rules \
                "${FIREWALL_ALLOW_IPTABLES_V4_RULES_FILE:-/etc/iptables/rules.v4}"; then
                FIREWALL_ALLOW_IPTABLES_V4_ADDED=no
            else
                FAILED=yes
                warn "iptables 新端口规则已回滚，但 IPv4 持久化保存失败"
            fi
        else
            FAILED=yes
            warn "回滚本次新增的 iptables ${PORT}/tcp 规则失败"
        fi
    fi
    if [ "${FIREWALL_ALLOW_IPTABLES_V6_ADDED:-no}" = yes ]; then
        if ip6tables -D INPUT -p tcp --dport "$PORT" -j ACCEPT \
            >/dev/null 2>&1; then
            if firewall_iptables_save_rules \
                "${FIREWALL_ALLOW_IPTABLES_V6_RULES_FILE:-/etc/iptables/rules.v6}"; then
                FIREWALL_ALLOW_IPTABLES_V6_ADDED=no
            else
                FAILED=yes
                warn "ip6tables 新端口规则已回滚，但 IPv6 持久化保存失败"
            fi
        else
            FAILED=yes
            warn "回滚本次新增的 ip6tables ${PORT}/tcp 规则失败"
        fi
    fi
    if [ "${FIREWALL_ALLOW_IPTABLES_V4_ADDED:-no}" = no ] \
        && [ "${FIREWALL_ALLOW_IPTABLES_V6_ADDED:-no}" = no ]; then
        FIREWALL_ALLOW_IPTABLES_ADDED=no
    elif [ "${FIREWALL_ALLOW_IPTABLES_V4_ADDED+x}" != x ] \
        && [ "${FIREWALL_ALLOW_IPTABLES_V6_ADDED+x}" != x ] \
        && [ "${FIREWALL_ALLOW_IPTABLES_ADDED:-no}" = yes ]; then
        if "$NETFILTER_CMD" -D INPUT -p tcp --dport "$PORT" -j ACCEPT \
            >/dev/null 2>&1; then
            if firewall_iptables_save_rules \
                "${FIREWALL_ALLOW_IPTABLES_RULES_FILE:-/etc/iptables/rules.v4}"; then
                FIREWALL_ALLOW_IPTABLES_ADDED=no
            else
                FAILED=yes
                warn "iptables 新端口规则已回滚，但持久化保存失败"
            fi
        else
            FAILED=yes
            warn "回滚本次新增的 iptables ${PORT}/tcp 规则失败"
        fi
    fi
    if [ "$FAILED" = no ]; then
        FIREWALL_ALLOW_DIRTY=no
        return 0
    fi
    return 1
}

firewall_allow_port() {
    local PORT="$1" FW_CONFIRM FAILED=no UFW_STATUS="" UFW_PORT_STATE=""
    local UFW_ALLOW_BEFORE=0 UFW_ALLOW_AFTER=0
    local RULES_FILE="" NETFILTER_CMD=iptables
    local UFW_ACTIVE=false FIREWALLD_ACTIVE=false IPTABLES_ACTIVE=false

    FIREWALL_ALLOW_UFW_ADDED=no
    FIREWALL_ALLOW_FIREWALLD_RUNTIME_ADDED=no
    FIREWALL_ALLOW_FIREWALLD_PERMANENT_ADDED=no
    FIREWALL_ALLOW_IPTABLES_ADDED=no
    FIREWALL_ALLOW_IPTABLES_V4_ADDED=no
    FIREWALL_ALLOW_IPTABLES_V6_ADDED=no
    FIREWALL_ALLOW_IPTABLES_RULES_FILE=""
    FIREWALL_ALLOW_IPTABLES_V4_RULES_FILE=""
    FIREWALL_ALLOW_IPTABLES_V6_RULES_FILE=""
    FIREWALL_ALLOW_NETFILTER_CMD=iptables
    FIREWALL_ALLOW_FIREWALLD_ZONE=""
    FIREWALL_ALLOW_DIRTY=no

    firewall_detect_backend || return 1
    NETFILTER_CMD="$FIREWALL_NETFILTER_CMD"
    RULES_FILE="${IPTABLES_RULES_FILE:-$FIREWALL_NETFILTER_RULES_DEFAULT}"
    FIREWALL_ALLOW_IPTABLES_RULES_FILE="$RULES_FILE"
    FIREWALL_ALLOW_NETFILTER_CMD="$NETFILTER_CMD"
    case "$FIREWALL_BACKEND" in
        ufw)
            UFW_ACTIVE=true
            UFW_STATUS="$FIREWALL_UFW_STATUS"
            ;;
        firewalld)
            FIREWALLD_ACTIVE=true
            FIREWALL_ALLOW_FIREWALLD_ZONE="$FIREWALL_FIREWALLD_ZONE"
            ;;
        iptables) IPTABLES_ACTIVE=true ;;
        nft-unsupported)
            error "检测到原生 nftables INPUT 丢弃策略；脚本无法安全推断并修改其规则，请先手工放行 ${PORT}/tcp"
            return 1
            ;;
        none)
        info "未检测到活跃防火墙，跳过端口放行"
        return 0
            ;;
        *)
            error "防火墙后端状态未知，拒绝继续修改 SSH 端口"
            return 1
            ;;
    esac

    echo ""
    warn "检测到活跃防火墙，是否自动放行新端口 ${PORT}/tcp？"
    read -rp "  自动放行？(Y/n，默认Y): " FW_CONFIRM
    FW_CONFIRM="${FW_CONFIRM:-y}"
    if ! echo "$FW_CONFIRM" | grep -qiE '^y(es)?$'; then
        error "未放行活跃防火墙中的新端口，已中止 SSH 端口切换；请手工放行后重试"
        return 1
    fi

    if [ "$UFW_ACTIVE" = true ]; then
        UFW_PORT_STATE=$(firewall_ufw_port_state "$UFW_STATUS" "$PORT")
        if [ "$UFW_PORT_STATE" = deny ]; then
            FAILED=yes
            error "ufw 存在 ${PORT}/tcp 的 DENY/REJECT 规则，拒绝把它误判为已放行"
        elif [ "$UFW_PORT_STATE" = policy ]; then
            FAILED=yes
            error "ufw 存在受接口或来源限制的 LIMIT 策略，拒绝自动覆盖：${PORT}/tcp"
        elif [ "$UFW_PORT_STATE" = allow ] || [ "$UFW_PORT_STATE" = limit ] \
            || [ "$UFW_PORT_STATE" = allow-limit ]; then
            info "ufw 已有 ${PORT}/tcp 放行规则"
        else
            UFW_ALLOW_BEFORE=$(firewall_ufw_allow_count "$UFW_STATUS" "$PORT")
        fi
        if [ "$UFW_PORT_STATE" = missing ] \
            && LC_ALL=C ufw insert 1 allow "${PORT}/tcp" >/dev/null 2>&1; then
            FIREWALL_ALLOW_UFW_ADDED=yes
            FIREWALL_ALLOW_DIRTY=yes
            UFW_STATUS=$(LC_ALL=C ufw status 2>/dev/null || true)
            UFW_ALLOW_AFTER=$(firewall_ufw_allow_count "$UFW_STATUS" "$PORT")
            if [ "$UFW_ALLOW_AFTER" -gt "$UFW_ALLOW_BEFORE" ] 2>/dev/null; then
                :
            fi
            if [ "$(firewall_ufw_port_state "$UFW_STATUS" "$PORT")" = allow ] \
                && [ "$UFW_ALLOW_AFTER" -gt "$UFW_ALLOW_BEFORE" ] 2>/dev/null; then
                info "ufw 已放行 ${PORT}/tcp ✓"
            else
                FAILED=yes
                error "ufw 写入后未检测到无条件放行规则：${PORT}/tcp"
            fi
        elif [ "$UFW_PORT_STATE" = missing ]; then
            FAILED=yes
            error "ufw 放行 ${PORT}/tcp 失败"
        fi
    fi
    if [ "$FIREWALLD_ACTIVE" = true ]; then
        if ! firewall-cmd --permanent --zone="$FIREWALL_ALLOW_FIREWALLD_ZONE" \
            --query-port="${PORT}/tcp" >/dev/null 2>&1; then
            if firewall-cmd --permanent --zone="$FIREWALL_ALLOW_FIREWALLD_ZONE" \
                --add-port="${PORT}/tcp" >/dev/null 2>&1; then
                FIREWALL_ALLOW_FIREWALLD_PERMANENT_ADDED=yes
                FIREWALL_ALLOW_DIRTY=yes
            else
                FAILED=yes
                error "firewalld 永久放行 ${PORT}/tcp 失败"
            fi
        fi
        if ! firewall-cmd --zone="$FIREWALL_ALLOW_FIREWALLD_ZONE" \
            --query-port="${PORT}/tcp" >/dev/null 2>&1; then
            if firewall-cmd --zone="$FIREWALL_ALLOW_FIREWALLD_ZONE" \
                --add-port="${PORT}/tcp" >/dev/null 2>&1; then
                FIREWALL_ALLOW_FIREWALLD_RUNTIME_ADDED=yes
                FIREWALL_ALLOW_DIRTY=yes
            else
                FAILED=yes
                error "firewalld 运行时放行 ${PORT}/tcp 失败"
            fi
        fi
        if [ "$FAILED" = no ]; then
            if firewall-cmd --permanent --zone="$FIREWALL_ALLOW_FIREWALLD_ZONE" \
                --query-port="${PORT}/tcp" >/dev/null 2>&1 \
                && firewall-cmd --zone="$FIREWALL_ALLOW_FIREWALLD_ZONE" \
                    --query-port="${PORT}/tcp" >/dev/null 2>&1; then
                info "firewalld 已放行 ${PORT}/tcp ✓"
            else
                FAILED=yes
                error "firewalld 写入后校验 ${PORT}/tcp 失败"
            fi
        fi
    fi
    if [ "$IPTABLES_ACTIVE" = true ]; then
        if [ "$FIREWALL_IPTABLES_V4_ACTIVE" = yes ]; then
            FIREWALL_ALLOW_IPTABLES_V4_RULES_FILE="${IPTABLES_RULES_FILE_V4:-${IPTABLES_RULES_FILE:-/etc/iptables/rules.v4}}"
            if ! firewall_iptables_persistence_available \
                "$FIREWALL_ALLOW_IPTABLES_V4_RULES_FILE"; then
                FAILED=yes
                error "无法确认 netfilter-persistent 会加载 IPv4 规则，拒绝只写运行时规则"
            elif iptables -I INPUT 1 -p tcp --dport "$PORT" -j ACCEPT \
                >/dev/null 2>&1; then
                FIREWALL_ALLOW_IPTABLES_V4_ADDED=yes
                FIREWALL_ALLOW_IPTABLES_ADDED=yes
                FIREWALL_ALLOW_DIRTY=yes
                if ! firewall_iptables_save_rules \
                    "$FIREWALL_ALLOW_IPTABLES_V4_RULES_FILE"; then
                    FAILED=yes
                    error "iptables 已放行运行时端口，但 IPv4 持久化保存失败"
                fi
            else
                FAILED=yes
                error "iptables 放行 ${PORT}/tcp 失败"
            fi
        fi
        if [ "$FIREWALL_IPTABLES_V6_ACTIVE" = yes ]; then
            FIREWALL_ALLOW_IPTABLES_V6_RULES_FILE="${IPTABLES_RULES_FILE_V6:-/etc/iptables/rules.v6}"
            if ! firewall_iptables_persistence_available \
                "$FIREWALL_ALLOW_IPTABLES_V6_RULES_FILE"; then
                FAILED=yes
                error "无法确认 netfilter-persistent 会加载 IPv6 规则，拒绝只写运行时规则"
            elif ip6tables -I INPUT 1 -p tcp --dport "$PORT" -j ACCEPT \
                >/dev/null 2>&1; then
                FIREWALL_ALLOW_IPTABLES_V6_ADDED=yes
                FIREWALL_ALLOW_IPTABLES_ADDED=yes
                FIREWALL_ALLOW_DIRTY=yes
                if ! firewall_iptables_save_rules \
                    "$FIREWALL_ALLOW_IPTABLES_V6_RULES_FILE"; then
                    FAILED=yes
                    error "ip6tables 已放行运行时端口，但 IPv6 持久化保存失败"
                fi
            else
                FAILED=yes
                error "ip6tables 放行 ${PORT}/tcp 失败"
            fi
        fi
        if [ "$FAILED" = no ]; then
            info "iptables/ip6tables 活跃地址族均已放行 ${PORT}/tcp ✓"
        fi
    fi
    if [ "$FAILED" = yes ]; then
        if firewall_rollback_allowed_port "$PORT"; then
            warn "已回滚本次新增的新端口防火墙规则"
        else
            error "部分新端口防火墙规则回滚失败，请立即手动核对 ${PORT}/tcp"
        fi
        return 1
    fi
    return 0
}

firewall_remove_port() {
    local PORT="$1"
    local CHANGED=no IPTABLES_CHANGED=no FAILED=no DELETE_COUNT=0
    local IPTABLES_V4_CHANGED=no IPTABLES_V6_CHANGED=no
    local RULES_FILE_V4="" RULES_FILE_V6=""
    local UFW_STATUS="" UFW_PORT_STATE="" UFW_ACTION=""
    local FIREWALLD_RUNTIME_PRESENT=no FIREWALLD_PERMANENT_PRESENT=no
    local FIREWALLD_ZONE=""
    FIREWALL_REMOVE_CHANGED=no

    firewall_detect_backend || return 1
    case "$FIREWALL_BACKEND" in
        none)
            return 0
            ;;
        nft-unsupported)
            error "检测到原生 nftables INPUT 丢弃策略，无法安全自动清理旧端口规则"
            return 1
            ;;
        ufw)
            UFW_STATUS="$FIREWALL_UFW_STATUS"
            UFW_PORT_STATE=$(firewall_ufw_port_state "$UFW_STATUS" "$PORT")
            case "$UFW_PORT_STATE" in
                allow) UFW_ACTION=allow ;;
                limit) UFW_ACTION=limit ;;
                allow-limit) UFW_ACTION="allow limit" ;;
                *) UFW_ACTION="" ;;
            esac
            for UFW_ACTION in $UFW_ACTION; do
                if LC_ALL=C ufw delete "$UFW_ACTION" "${PORT}/tcp" >/dev/null 2>&1; then
                    CHANGED=yes
                else
                    FAILED=yes
                    warn "ufw 旧端口 ${UFW_ACTION} 规则删除失败：${PORT}/tcp"
                fi
            done
            [ "$CHANGED" != yes ] || [ "$FAILED" = yes ] \
                || info "ufw 已关闭旧端口 ${PORT}/tcp ✓"
            ;;
        firewalld)
            FIREWALLD_ZONE="$FIREWALL_FIREWALLD_ZONE"
            if firewall-cmd --zone="$FIREWALLD_ZONE" \
                --query-port="${PORT}/tcp" >/dev/null 2>&1; then
                FIREWALLD_RUNTIME_PRESENT=yes
            fi
            if firewall-cmd --permanent --zone="$FIREWALLD_ZONE" \
                --query-port="${PORT}/tcp" >/dev/null 2>&1; then
                FIREWALLD_PERMANENT_PRESENT=yes
            fi
            if [ "$FIREWALLD_RUNTIME_PRESENT" = yes ]; then
                if firewall-cmd --zone="$FIREWALLD_ZONE" \
                    --remove-port="${PORT}/tcp" >/dev/null 2>&1; then
                    CHANGED=yes
                else
                    FAILED=yes
                    warn "firewalld 运行时旧端口规则删除失败：${PORT}/tcp"
                fi
            fi
            if [ "$FIREWALLD_PERMANENT_PRESENT" = yes ]; then
                if firewall-cmd --permanent --zone="$FIREWALLD_ZONE" \
                    --remove-port="${PORT}/tcp" >/dev/null 2>&1; then
                    CHANGED=yes
                else
                    FAILED=yes
                    warn "firewalld 永久旧端口规则删除失败：${PORT}/tcp"
                fi
            fi
            if [ "$FIREWALLD_RUNTIME_PRESENT" = yes ] \
                || [ "$FIREWALLD_PERMANENT_PRESENT" = yes ]; then
                [ "$FAILED" = yes ] \
                    || info "firewalld 已关闭旧端口 ${PORT}/tcp ✓"
            fi
            ;;
        iptables)
            RULES_FILE_V4="${IPTABLES_RULES_FILE_V4:-${IPTABLES_RULES_FILE:-/etc/iptables/rules.v4}}"
            RULES_FILE_V6="${IPTABLES_RULES_FILE_V6:-/etc/iptables/rules.v6}"
            if [ "$FIREWALL_IPTABLES_V4_ACTIVE" = yes ]; then
                if iptables -C INPUT -p tcp --dport "$PORT" -j ACCEPT \
                    >/dev/null 2>&1 \
                    && ! firewall_iptables_persistence_available "$RULES_FILE_V4"; then
                    error "无法证明 IPv4 规则会在启动时加载，拒绝只删除运行时旧端口规则"
                    return 1
                fi
                while iptables -C INPUT -p tcp --dport "$PORT" -j ACCEPT \
                    >/dev/null 2>&1; do
                    if ! iptables -D INPUT -p tcp --dport "$PORT" -j ACCEPT \
                        >/dev/null 2>&1; then
                        FAILED=yes
                        warn "iptables 旧端口规则删除失败：${PORT}/tcp"
                        break
                    fi
                    CHANGED=yes
                    IPTABLES_CHANGED=yes
                    IPTABLES_V4_CHANGED=yes
                    DELETE_COUNT=$((DELETE_COUNT+1))
                    if [ "$DELETE_COUNT" -ge 256 ]; then
                        FAILED=yes
                        warn "iptables 旧端口规则数量异常，已停止继续删除：${PORT}/tcp"
                        break
                    fi
                done
                if [ "$IPTABLES_V4_CHANGED" = yes ] \
                    && ! firewall_iptables_save_rules "$RULES_FILE_V4"; then
                    warn "IPv4 运行时规则已更新，但持久化保存失败"
                    return 1
                fi
            fi
            if [ "$FIREWALL_IPTABLES_V6_ACTIVE" = yes ]; then
                if ip6tables -C INPUT -p tcp --dport "$PORT" -j ACCEPT \
                    >/dev/null 2>&1 \
                    && ! firewall_iptables_persistence_available "$RULES_FILE_V6"; then
                    error "无法证明 IPv6 规则会在启动时加载，拒绝只删除运行时旧端口规则"
                    return 1
                fi
                while ip6tables -C INPUT -p tcp --dport "$PORT" -j ACCEPT \
                    >/dev/null 2>&1; do
                    if ! ip6tables -D INPUT -p tcp --dport "$PORT" -j ACCEPT \
                        >/dev/null 2>&1; then
                        FAILED=yes
                        warn "ip6tables 旧端口规则删除失败：${PORT}/tcp"
                        break
                    fi
                    CHANGED=yes
                    IPTABLES_CHANGED=yes
                    IPTABLES_V6_CHANGED=yes
                    DELETE_COUNT=$((DELETE_COUNT+1))
                    if [ "$DELETE_COUNT" -ge 256 ]; then
                        FAILED=yes
                        warn "ip6tables 旧端口规则数量异常，已停止继续删除：${PORT}/tcp"
                        break
                    fi
                done
                if [ "$IPTABLES_V6_CHANGED" = yes ] \
                    && ! firewall_iptables_save_rules "$RULES_FILE_V6"; then
                    warn "IPv6 运行时规则已更新，但持久化保存失败"
                    return 1
                fi
            fi
            [ "$IPTABLES_CHANGED" != yes ] \
                || info "iptables 已关闭旧端口 ${PORT}/tcp ✓"
            ;;
    esac

    FIREWALL_REMOVE_CHANGED="$CHANGED"
    [ "$FAILED" = no ]
}
