#!/bin/bash
# Generated by build.sh from src/. Edit module sources, then rebuild this release file.

# ============================================================
#  VPS 开荒脚本 V3.9.31 — 银趴火山帮
#  功能：SSH管理 / Fail2ban / BBR TCP 调优
#  V3.9.31: DDNS 支持 IPv4 A 与 IPv6 AAAA 分别设置，可同域名或不同子域名同时更新
#  V3.9.30: SSH 改端口流程改为先确认新端口可登录，再决定是否关闭旧端口
#  V3.9.29: 修复每日日报和续费提醒同日重复推送，并转义 Telegram HTML 主机显示名
#  V3.9.28: 首页采用清爽运维风，缩小 IMPART OPS 字幅并增加副标题
#  V3.9.27: 统一所有交互界面标题为 VPS TOOLS · 版本号 + 当前模块名
#  V3.9.26: 流量监控启用时新增“是否清除旧记录”确认，保留或重置统计由用户决定
#  V3.9.25: 安全与诊断工具箱新增系统 hostname 修改，自动校验并同步 /etc/hostname 与 /etc/hosts
#  V3.9.24: 续费提醒新增“我已续费”，确认后跳过当前周期并从下一周期继续提醒
#  V3.9.23: 日报、流量、续费、资源告警子页均支持立即推送当前实时快照
#  V3.9.22: 重排监控告警中心流程，新增快速启用、通知/日报/流量/续费/资源/高级独立子页
#  V3.9.21: 日报启用时自动安装精确定时任务，避免 23:59 等时间被 10 分钟轮询错过
#  V3.9.20: 监控告警增加趋势摘要与告警分级，日报/测试快照同步展示
#  V3.9.19: 监控告警中心增强，支持冷却/静默/恢复通知/检查项开关/最近告警记录
#  V3.9.18: 新增配置体检与诊断包入口，并引入 manifest 支撑更新校验
#  V3.9.17: 服务管理统一使用 systemd_available 检测，减少 cron/容器环境误判
#  V3.9.16: 流量监控阈值设置与启用逻辑拆分，避免修改阈值时重置今日与周期累计
#  V3.8.6: 新增配置导出/导入与统一回滚中心入口
#  V3.8.5: 新增从 URL 拉取 Compose 文件、自动校验并部署的入口，
#          支持先预览再落盘执行 `docker compose up -d --pull always`
#  V3.8.4: 新增 Docker Engine 一键安装、容器生命周期管理、日志/Shell，
#          Compose 服务安全升级与普通容器镜像更新检查
#  V3.8.3: 新增跨发行版常用软件多选安装，以及带容器检测、脚本语法校验、
#          固定确认词和 SSH 参数继承的一键 DD / Linux 系统重装安全向导
#  V3.8.2: 统一剩余子页面：BBR 多级向导、Fail2ban、Swap、换源、日志、
#          NFT 访问控制及安装页面全部接入响应式菜单、提示和暂停组件
#  V3.8.1: 重构响应式终端界面：宽/窄屏自适应、统一状态仪表盘、菜单、提示，
#          支持 NO_COLOR 与非交互终端，压缩重复标题并改善主要模块导航
#  V3.8.0: 源码模块化并生成单文件发行版；新增跨发行版/故障注入测试、备份保留、
#          配置变更预览、资源健康检查和系统更新管理
#  V3.7.0: 新增系统安全体检、登录安全日志、网络诊断、统一配置备份恢复、
#          操作审计、防断联延迟回滚、DNS 后端适配、脚本版本回滚与 SHA256 校验
#  V3.6.3: IPv4/IPv6 配置菜单新增“设置 IPv6 优先”，可恢复系统默认地址优先级
#  V3.6.2: BBR 模块增强：sysctl 权限探测无副作用、tc service 动态找 tc/网卡、
#          不支持 sysctl 参数注释持久化、Alpine 内核包安装需确认、增加诊断入口
#  V3.6.1: 修复删除最后一个 SSH 公钥不生效、DDNS 备用日志路径不生效、
#          nftables 应用失败误报成功、initcwnd 无网关默认路由失败
#  V3.6.0: Fail2ban 加 mode=aggressive(纯公钥机抓扫描)、journalmatch 双服务名
#          (兼容 Debian ssh / RedHat sshd)、jail.local 已存在改为备份后重写(原跳过)
#  V3.5.9: SSH改端口/配置失败自动回滚、改端口延后删旧(防锁死)、防火墙卸载不再
#          flush全表(只删自身规则)、DDNS IPv4严格校验、服务操作统一svc_*封装、
#          默认网卡用 ip route get、Caddy 配置临时验证通过才写入
#  V3.5.8: 修复 bbr-tune.sh 独立版缺失 4 个辅助函数(ensure_conntrack_module/
#          svc_daemon_reload/svc_enable/svc_disable)，独立运行限速/场景预设不再中断
#  V3.5.7: DDNS 状态区增加「最后一次 IP 变更时间 + 新旧 IP」显示
#  V3.5.6: 新增 UDP 缓冲(QUIC/Hysteria2)、场景预设加端口范围/tw_buckets/file-max
#          防高并发端口耗尽、应用场景预设后检测代理 service LimitNOFILE
#  V3.5.5: BBR 限速改 htb 整形+fq pacing(保 BBR)、burst 随速率缩放、
#          切换预设复位残留场景键、新增 32MB 缓冲档、修 BDP 双截断
# ============================================================

# ── 解释器守卫：本脚本依赖 bash（数组 / [[ ]] / here-string 等）──
# 仅用 POSIX 语法编写，确保在 ash/dash 下也能解析并 fail-fast。
if [ -z "$BASH_VERSION" ]; then
    if command -v bash >/dev/null 2>&1; then
        exec bash "$0" "$@"
    fi
    echo "本脚本需要 bash 运行，当前 shell 不是 bash 且系统未安装 bash。"
    echo "请先安装 bash 后重试："
    echo "  Alpine:   apk add bash"
    echo "  OpenWrt:  opkg update && opkg install bash"
    echo "  Debian:   apt-get install -y bash"
    echo "  CentOS:   yum install -y bash"
    exit 1
fi

SSHD_CONFIG="/etc/ssh/sshd_config"
# 优先使用 /root/.ssh/authorized_keys，兼容系统预装公钥路径
AUTH_KEYS="${HOME}/.ssh/authorized_keys"
[ "$(id -u)" = "0" ] && AUTH_KEYS="/root/.ssh/authorized_keys"
VPS_DATA_DIR="/var/lib/vps-tools"
# shellcheck disable=SC2034 # used by management modules in the concatenated release script
VPS_BACKUP_DIR="$VPS_DATA_DIR/backups"
# shellcheck disable=SC2034 # used by management modules in the concatenated release script
VPS_VERSION_DIR="$VPS_DATA_DIR/versions"
VPS_AUDIT_LOG="/var/log/vps-tools-audit.log"
VPS_BACKUP_KEEP="${VPS_BACKUP_KEEP:-20}"
case "$VPS_BACKUP_KEEP" in ''|*[!0-9]*) VPS_BACKUP_KEEP=20 ;; esac
[ "$VPS_BACKUP_KEEP" -ge 1 ] || VPS_BACKUP_KEEP=20

if [ -n "${NO_COLOR:-}" ] || [ "${TERM:-}" = "dumb" ] || [ ! -t 1 ]; then
    RED="" GREEN="" YELLOW="" BLUE="" CYAN="" BOLD="" DIM="" NC=""
else
    RED=$'\033[0;31m'
    GREEN=$'\033[0;32m'
    YELLOW=$'\033[1;33m'
    BLUE=$'\033[0;34m'
    CYAN=$'\033[0;36m'
    BOLD=$'\033[1m'
    DIM=$'\033[2m'
    NC=$'\033[0m'
fi

info()  { echo -e "  ${GREEN}✓${NC}  $1"; }
warn()  { echo -e "  ${YELLOW}!${NC}  $1"; }
error() { echo -e "  ${RED}×${NC}  $1"; }

audit_action() {
    local ACTION="$1" RESULT="${2:-INFO}" SOURCE_IP="local"
    [ -n "${SSH_CONNECTION:-}" ] && SOURCE_IP=$(echo "$SSH_CONNECTION" | awk '{print $1}')
    mkdir -p "$(dirname "$VPS_AUDIT_LOG")" 2>/dev/null || true
    printf '%s\t%s\t%s\t%s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$RESULT" "$SOURCE_IP" "$ACTION" \
        2>/dev/null >> "$VPS_AUDIT_LOG" || true
    chmod 600 "$VPS_AUDIT_LOG" 2>/dev/null || true
}

# 兼容 dumb 终端（OpenWrt / tmux 等不支持 clear 的环境）
safe_clear() {
    if [ -n "${TERM:-}" ] && [ "$TERM" != "dumb" ]; then
        clear 2>/dev/null || true
    fi
}

systemd_available() {
    command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]
}

# 主菜单品牌字幅
volcano_art_banner() {
    ui_refresh_dimensions
    echo -e "${RED}${BOLD}"
    cat << 'BANNER_EOF'
    ______  _______  ___    ____  ______   ____  ____  _____
   /  _/  |/  / __ \/   |  / __ \/_  __/  / __ \/ __ \/ ___/
   / // /|_/ / /_/ / /| | / /_/ / / /    / / / / /_/ /\__ \
 _/ // /  / / ____/ ___ |/ _, _/ / /    / /_/ / ____/___/ /
/___/_/  /_/_/   /_/  |_/_/ |_| /_/     \____/_/    /____/
BANNER_EOF
    echo -e "${NC}"
}

# ── 可见宽度计算（用 python3，中文=2，ASCII=1）────────────
vis_len() {
    python3 -c "
import unicodedata, sys
s = sys.argv[1]
print(sum(2 if unicodedata.east_asian_width(c) in ('W','F') else 1 for c in s))
" "$1" 2>/dev/null || echo "${#1}"
}

# ── 响应式终端布局 ────────────────────────────────────────
BOX_W=64
UI_COMPACT=0
APP_UI_TITLE="VPS TOOLS"
APP_VERSION="V3.9.31"
APP_SUBTITLE="VPS 开荒脚本 · 银趴火山帮"

ui_refresh_dimensions() {
    local COLS="${COLUMNS:-}"
    if ! echo "$COLS" | grep -qE '^[0-9]+$'; then
        COLS=$(tput cols 2>/dev/null || echo 80)
    fi
    [ "$COLS" -gt 76 ] && COLS=76
    [ "$COLS" -lt 36 ] && COLS=36
    BOX_W=$COLS
    UI_COMPACT=0
    if [ "$BOX_W" -lt 66 ]; then UI_COMPACT=1; fi
}

ui_repeat() {
    local CHAR="$1" COUNT="$2" i
    for ((i=0; i<COUNT; i++)); do printf '%s' "$CHAR"; done
}

box_top() { ui_refresh_dimensions; printf '%s' "${BOLD}${CYAN}"; ui_repeat "━" "$BOX_W"; printf '%s\n' "$NC"; }
box_bot() { printf '%s' "${BOLD}${CYAN}"; ui_repeat "━" "$BOX_W"; printf '%s\n' "$NC"; }
box_sep() { printf '%s' "${DIM}${CYAN}"; ui_repeat "─" "$BOX_W"; printf '%s\n' "$NC"; }

# 居中标题行（只传纯文本，自动居中）
box_title() {
    local TEXT="$1"
    local LEN; LEN=$(vis_len "$TEXT")
    local INNER=$((BOX_W - 2))
    local PAD_TOTAL=$(( INNER - LEN ))
    [ "$PAD_TOTAL" -lt 0 ] && PAD_TOTAL=0
    local PAD_L=$(( PAD_TOTAL / 2 ))
    local PAD_R=$(( PAD_TOTAL - PAD_L ))
    printf '%*s' "$PAD_L" ''
    printf "${BOLD}${CYAN}%s${NC}" "$TEXT"
    printf '%*s' "$PAD_R" ''
    printf "\n"
}

# 普通内容行：PLAIN=纯文本(算宽度)  COLORED=带色码(显示用)
# 用法: box_line "纯文本" "带色码文本"
box_line() {
    local COLORED="${2:-$1}"
    echo -e "$COLORED"
}

# 空行
box_empty() {
    echo ""
}

# ── 内层分隔线（与主框线同宽对齐，dim 青，统一替代各处 seq 1 38）──
menu_div() { ui_refresh_dimensions; printf '%s' "${DIM}${CYAN}"; ui_repeat "─" "$BOX_W"; printf '%s\n' "$NC"; }

app_header_line() {
    echo -e "  ${DIM}${APP_UI_TITLE}  ·  ${APP_VERSION}${NC}"
}

app_subtitle_line() {
    echo -e "  ${BOLD}${CYAN}${APP_SUBTITLE}${NC}"
}

# ── 段标题（❯ 前缀，统一替代 [xxx] 方括号风格）──
menu_group() { echo -e "  ${CYAN}${BOLD}◆ ${1}${NC}"; }

# ── 菜单项（统一缩进与配色）。用法: menu_item "1" "SSH 工具集" [颜色]──
menu_item() {
    local KEY="$1" LABEL="$2" COL="${3:-$GREEN}"
    echo -e "    ${COL}${BOLD}${KEY}${NC}  ${LABEL}"
}

menu_pair() {
    local K1="$1" L1="$2" K2="${3:-}" L2="${4:-}" COL1="${5:-$GREEN}" COL2="${6:-$GREEN}"
    ui_refresh_dimensions
    if [ "$UI_COMPACT" = "1" ] || [ -z "$K2" ]; then
        menu_item "$K1" "$L1" "$COL1"
        [ -n "$K2" ] && menu_item "$K2" "$L2" "$COL2"
        return
    fi
    local LEFT="${K1}  ${L1}" TARGET=$((BOX_W / 2 - 3)) LEN PAD
    LEN=$(vis_len "$LEFT"); PAD=$((TARGET - LEN)); [ "$PAD" -lt 2 ] && PAD=2
    printf '    %s%s%s' "$COL1$BOLD" "$K1" "$NC"
    printf '  %s' "$L1"
    printf '%*s' "$PAD" ''
    printf '%s%s%s  %s\n' "$COL2$BOLD" "$K2" "$NC" "$L2"
}

status_dot() {
    local STATE="$1"
    case "$STATE" in
        active|running|yes|on|已启用|运行中) echo -e "${GREEN}●${NC}" ;;
        inactive|stopped|no|off|已停止) echo -e "${RED}●${NC}" ;;
        *) echo -e "${YELLOW}●${NC}" ;;
    esac
}

status_pair() {
    local L1="$1" V1="$2" S1="$3" L2="${4:-}" V2="${5:-}" S2="${6:-}" D1 D2 C1 C2
    case "$S1" in active|running|yes|on|已启用|运行中) C1="$GREEN" ;; inactive|stopped|no|off|已停止) C1="$RED" ;; *) C1="$YELLOW" ;; esac
    case "$S2" in active|running|yes|on|已启用|运行中) C2="$GREEN" ;; inactive|stopped|no|off|已停止) C2="$RED" ;; *) C2="$YELLOW" ;; esac
    D1="${C1}●${NC}"; D2="${C2}●${NC}"
    ui_refresh_dimensions
    if [ "$UI_COMPACT" = "1" ] || [ -z "$L2" ]; then
        echo -e "  $D1  ${DIM}${L1}${NC}  ${BOLD}${V1}${NC}"
        [ -n "$L2" ] && echo -e "  $D2  ${DIM}${L2}${NC}  ${BOLD}${V2}${NC}"
        return
    fi
    local PLAIN="●  ${L1}  ${V1}" TARGET=$((BOX_W / 2)) LEN PAD
    LEN=$(vis_len "$PLAIN"); PAD=$((TARGET - LEN)); [ "$PAD" -lt 2 ] && PAD=2
    echo -en "  $D1  ${DIM}${L1}${NC}  ${BOLD}${V1}${NC}"
    printf '%*s' "$PAD" ''
    echo -e "$D2  ${DIM}${L2}${NC}  ${BOLD}${V2}${NC}"
}

ui_hint() { echo -e "  ${DIM}› $1${NC}"; }
ui_prompt() { printf '  %s›%s %s' "$CYAN$BOLD" "$NC" "$1"; }
ui_pause() { echo ""; read -rp "$(ui_prompt '按 Enter 返回')" _; }
ui_continue() { echo ""; read -rp "$(ui_prompt '按 Enter 继续')" _; }


# ── 通用编辑器（兼容 Alpine/OpenWrt 等精简系统）────────────
get_editor() {
    for ed in nano vi vim; do
        command -v "$ed" &>/dev/null && echo "$ed" && return
    done
    echo "vi"  # 最后兜底，几乎所有系统都有 vi
}

open_editor() {
    local FILE="$1"
    local ED; ED=$(get_editor)
    if ! command -v "$ED" &>/dev/null; then
        # vi 也没有，尝试安装 nano
        warn "未找到编辑器，尝试安装 nano..."
        pkg_install nano &>/dev/null || pkg_install vim &>/dev/null || true
        ED=$(get_editor)
    fi
    "$ED" "$FILE"
}

# ── 确保 sysctl 可用（Alpine 需要 procps 或 sysctl 包）────
# 加载 nf_conntrack 模块（中转/落地机需要）
ensure_conntrack_module() {
    lsmod 2>/dev/null | grep -q "^nf_conntrack" && return 0
    modprobe nf_conntrack 2>/dev/null
}

ensure_sysctl() {
    command -v sysctl &>/dev/null && return 0
    warn "sysctl 未找到，正在安装..."
    if command -v apk &>/dev/null; then
        apk add --no-cache procps 2>/dev/null || apk add --no-cache sysctl 2>/dev/null || true
    else
        pkg_install procps 2>/dev/null || true
    fi
    command -v sysctl &>/dev/null && return 0
    error "sysctl 安装失败，请手动执行：apk add procps"
    return 1
}


# iptables/ip6tables 残留规则清理（卸载防火墙时使用）
clear_iptables_residue() {
    # 安全清理：只删除本脚本可能残留的规则，绝不 flush 全表、绝不改默认策略。
    # 旧版会 iptables -F + 设 ACCEPT，会瞬间裸奔并抹掉 NFT 转发/代理/用户自有规则。
    # ufw --force reset / firewalld 卸载本身已清掉各自规则，这里无需再 flush。
    if command -v iptables &>/dev/null; then
        # 删除本脚本 SSH 放行可能残留的 INPUT ACCEPT 规则（逐条删，删到没有为止）
        local _p
        for _p in $(get_config "Port" 2>/dev/null) 22; do
            [ -n "$_p" ] || continue
            while iptables -C INPUT -p tcp --dport "$_p" -j ACCEPT 2>/dev/null; do
                iptables -D INPUT -p tcp --dport "$_p" -j ACCEPT 2>/dev/null || break
            done
        done
    fi
    info "已清理本脚本残留规则（未触碰默认策略与其它规则）"
}

# 统一标题栏
print_header() {
    safe_clear
    echo ""
    box_top
    app_header_line
    echo -e "  ${BOLD}${CYAN}$1${NC}"
    box_bot
    echo ""
}


# ── 兼容工具函数（支持 BusyBox / Alpine）─────────────────

# 替代 grep -oP '(?:maxrate|rate) \K\S+'
# 替代 grep -oE 'initcwnd [0-9]+' | awk '{print $2}'
# 检测服务管理器并重启 SSH
restart_ssh() {
    if systemd_available; then
        systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service sshd restart 2>/dev/null || rc-service ssh restart 2>/dev/null
    elif command -v service &>/dev/null; then
        service ssh restart 2>/dev/null || service sshd restart 2>/dev/null
    else
        return 1
    fi
}

# 检测服务管理器并重启 fail2ban
restart_fail2ban() {
    if systemd_available; then
        systemctl restart fail2ban 2>/dev/null && return 0
    fi
    if command -v rc-service &>/dev/null; then
        rc-service fail2ban restart 2>/dev/null && return 0
    fi
    if command -v service &>/dev/null; then
        service fail2ban restart 2>/dev/null && return 0
    fi
    [ -x /etc/init.d/fail2ban ] && /etc/init.d/fail2ban restart 2>/dev/null
}

# 检测服务管理器并启动/停止 fail2ban
start_fail2ban() {
    # 确保 socket 目录存在（tmpfs 重启后会消失）
    mkdir -p /var/run/fail2ban 2>/dev/null
    chmod 755 /var/run/fail2ban 2>/dev/null

    # 写入 tmpfiles.d 确保重启后自动创建目录
    if command -v systemd-tmpfiles &>/dev/null; then
        echo "d /var/run/fail2ban 0755 root root -" > /etc/tmpfiles.d/fail2ban.conf 2>/dev/null
        systemd-tmpfiles --create /etc/tmpfiles.d/fail2ban.conf 2>/dev/null || true
    fi

    # 优先尝试 systemctl，失败则回退 service / rc-service
    if systemd_available; then
        systemctl start fail2ban 2>/dev/null && return 0
    fi
    if command -v rc-service &>/dev/null; then
        rc-service fail2ban start 2>/dev/null && return 0
    fi
    if command -v service &>/dev/null; then
        service fail2ban start 2>/dev/null && return 0
    fi
    # 最后回退：直接调用 init.d 脚本
    [ -x /etc/init.d/fail2ban ] && /etc/init.d/fail2ban start 2>/dev/null
}
stop_fail2ban() {
    if systemd_available; then
        systemctl stop fail2ban 2>/dev/null && return 0
    fi
    if command -v rc-service &>/dev/null; then
        rc-service fail2ban stop 2>/dev/null && return 0
    fi
    if command -v service &>/dev/null; then
        service fail2ban stop 2>/dev/null && return 0
    fi
    [ -x /etc/init.d/fail2ban ] && /etc/init.d/fail2ban stop 2>/dev/null
}

# ── 系统检测工具 ──────────────────────────────────────────

# 检测包管理器
pkg_install() {
    local PKG="$1"
    if command -v apt-get &>/dev/null; then
        apt-get update -qq 2>/dev/null
        apt-get install -y "$PKG" 2>/dev/null
    elif command -v apk &>/dev/null; then
        apk add --no-cache "$PKG" 2>/dev/null
    elif command -v yum &>/dev/null; then
        yum install -y "$PKG" 2>/dev/null
    elif command -v dnf &>/dev/null; then
        dnf install -y "$PKG" 2>/dev/null
    elif command -v pacman &>/dev/null; then
        pacman -Sy --noconfirm "$PKG" 2>/dev/null
    else
        return 1
    fi
}

pkg_remove() {
    local PKG="$1"
    if command -v apt-get &>/dev/null; then
        apt-get remove -y "$PKG" 2>/dev/null
    elif command -v apk &>/dev/null; then
        apk del "$PKG" 2>/dev/null
    elif command -v yum &>/dev/null; then
        yum remove -y "$PKG" 2>/dev/null
    elif command -v dnf &>/dev/null; then
        dnf remove -y "$PKG" 2>/dev/null
    else
        return 1
    fi
}

# 通用服务启用（开机自启）
svc_enable() {
    local SVC="$1"
    if systemd_available; then
        systemctl unmask "$SVC" 2>/dev/null || true
        systemctl enable "$SVC" --quiet 2>/dev/null || true
    elif command -v rc-update &>/dev/null; then
        rc-update add "$SVC" default 2>/dev/null
    elif command -v update-rc.d &>/dev/null; then
        update-rc.d "$SVC" enable 2>/dev/null
    fi
}

svc_disable() {
    local SVC="$1"
    if command -v systemctl &>/dev/null; then
        systemctl disable "$SVC" --quiet 2>/dev/null
    elif command -v rc-update &>/dev/null; then
        rc-update del "$SVC" 2>/dev/null
    fi
}

# 通用服务 start/stop/restart 封装（systemd / OpenRC / sysvinit）
# OpenRC 服务名常带不同后缀，systemd 用 .service；调用方传裸名即可。
# 获取默认出口网卡：ip route get 比 awk '/^default/' 更准
# （多默认路由 / 策略路由 / IPv6-only 时不易取错），失败回退旧法
default_iface() {
    local DEV
    DEV=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')
    [ -z "$DEV" ] && DEV=$(ip -6 route get 2606:4700:4700::1111 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')
    [ -z "$DEV" ] && DEV=$(ip route 2>/dev/null | awk '/^default/{print $5; exit}')
    echo "$DEV"
}

svc_start() {
    local SVC="$1"
    if systemd_available; then
        systemctl start "$SVC" 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service "$SVC" start 2>/dev/null
    elif command -v service &>/dev/null; then
        service "$SVC" start 2>/dev/null
    else
        return 1
    fi
}

svc_stop() {
    local SVC="$1"
    if systemd_available; then
        systemctl stop "$SVC" 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service "$SVC" stop 2>/dev/null
    elif command -v service &>/dev/null; then
        service "$SVC" stop 2>/dev/null
    else
        return 1
    fi
}

svc_restart() {
    local SVC="$1"
    if systemd_available; then
        systemctl restart "$SVC" 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service "$SVC" restart 2>/dev/null
    elif command -v service &>/dev/null; then
        service "$SVC" restart 2>/dev/null
    else
        return 1
    fi
}

# 通用服务 is-active 检测
svc_is_active() {
    local SVC="$1"
    if command -v systemctl &>/dev/null; then
        systemctl is-active --quiet "$SVC" 2>/dev/null
    elif command -v rc-service &>/dev/null; then
        rc-service "$SVC" status &>/dev/null
    elif command -v service &>/dev/null; then
        service "$SVC" status &>/dev/null
    else
        return 1
    fi
}

# systemctl daemon-reload 兼容（OpenRC 不需要）
svc_daemon_reload() {
    command -v systemctl &>/dev/null && systemctl daemon-reload 2>/dev/null || true
}

# 获取 OS codename（兼容无 lsb_release 的系统）
get_codename() {
    if command -v lsb_release &>/dev/null; then
        lsb_release -cs 2>/dev/null
    elif [ -f /etc/os-release ]; then
        grep VERSION_CODENAME /etc/os-release | cut -d= -f2 | tr -d '"'
    elif [ -f /etc/debian_version ]; then
        cat /etc/debian_version | cut -d. -f1
    else
        echo "unknown"
    fi
}

# ── 权限检查 ──────────────────────────────────────────────
if [ "$EUID" -ne 0 ] && [ "${VPS_TOOLS_TEST_MODE:-0}" != "1" ] && [ "${1:-}" != "--help" ] && [ "${1:-}" != "-h" ] && [ "${1:-}" != "help" ]; then
    echo -e "${RED}[ERROR]${NC} 请使用 root 权限运行：sudo bash $0"
    exit 1
fi

# ── 通用工具函数 ──────────────────────────────────────────
get_config() {
    grep -E "^[[:space:]]*$1[[:space:]]" "$SSHD_CONFIG" 2>/dev/null \
        | tail -1 | awk '{print $2}'
}

set_config_file() {
    local FILE="$1" KEY="$2" VALUE="$3"
    if grep -qE "^#?[[:space:]]*${KEY}[[:space:]]" "$FILE"; then
        sed -i "s|^#\?[[:space:]]*${KEY}[[:space:]].*|${KEY} ${VALUE}|" "$FILE"
    else
        echo "${KEY} ${VALUE}" >> "$FILE"
    fi
}

set_config() {
    set_config_file "$SSHD_CONFIG" "$1" "$2"
}

backup_config() {
    local BACKUP
    BACKUP="$SSHD_CONFIG.bak.$(date +%Y%m%d_%H%M%S)"
    cp "$SSHD_CONFIG" "$BACKUP"
    LAST_SSHD_BACKUP="$BACKUP"   # 供 apply_and_restart 失败时回滚
    info "配置已备份：$BACKUP"
}

apply_and_restart() {
    # 失败时自动回滚到最近备份，避免把自己锁在外面
    _ssh_rollback() {
        if [ -n "${LAST_SSHD_BACKUP:-}" ] && [ -f "$LAST_SSHD_BACKUP" ]; then
            cp "$LAST_SSHD_BACKUP" "$SSHD_CONFIG" 2>/dev/null
            warn "已回滚 sshd_config 到备份：$LAST_SSHD_BACKUP"
            if sshd -t 2>/dev/null && restart_ssh; then
                info "已用备份配置恢复 SSH 服务 ✓"
            else
                error "回滚后仍异常，请立即手动检查 sshd_config 与 SSH 服务！"
            fi
        else
            error "未找到可回滚的备份，请立即手动检查 SSH 配置！"
        fi
    }
    if ! sshd -t 2>/dev/null; then
        error "配置文件语法错误，自动回滚中..."
        _ssh_rollback
        return 1
    fi
    if restart_ssh; then
        info "SSH 服务已重启 ✓"
    else
        error "SSH 服务重启失败，自动回滚中..."
        _ssh_rollback
        return 1
    fi
}

list_keys() {
    if [ ! -f "$AUTH_KEYS" ] || ! grep -qE '^(ssh-rsa|ssh-ed25519|ecdsa-sha2|sk-ssh|sk-ecdsa|ssh-dss) ' "$AUTH_KEYS" 2>/dev/null; then
        echo -e "  ${YELLOW}（暂无公钥）${NC}"
        return 1
    fi
    local i=1
    while IFS= read -r line; do
        if echo "$line" | grep -qE '^(ssh-rsa|ssh-ed25519|ecdsa-sha2|sk-ssh|sk-ecdsa|ssh-dss) '; then
            local TYPE COMMENT FINGER
            TYPE=$(echo "$line" | awk '{print $1}')
            COMMENT=$(echo "$line" | awk '{print $3}')
            FINGER=$(echo "$line" | ssh-keygen -lf /dev/stdin 2>/dev/null | awk '{print $2}' || echo "N/A")
            echo -e "  ${GREEN}[$i]${NC} ${BOLD}$TYPE${NC}"
            echo -e "      ${DIM}指纹：${NC}${BLUE}$FINGER${NC}"
            echo -e "      ${DIM}备注：${NC}${YELLOW}${COMMENT:-（无备注）}${NC}"
            echo ""
            i=$((i+1))
        fi
    done < "$AUTH_KEYS"
    return 0
}

firewall_allow_port() {
    local PORT="$1"
    local UFW_ACTIVE=false FIREWALLD_ACTIVE=false IPTABLES_ACTIVE=false

    command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -q "Status: active" && UFW_ACTIVE=true
    command -v firewall-cmd &>/dev/null && svc_is_active firewalld && FIREWALLD_ACTIVE=true
    if command -v iptables &>/dev/null; then
        local RULES
        RULES=$(iptables -L INPUT --line-numbers 2>/dev/null             | grep -vc "^Chain\|^num\|^$\|ACCEPT.*all.*anywhere.*anywhere")
        [ "$RULES" -gt 0 ] && IPTABLES_ACTIVE=true
    fi

    if [ "$UFW_ACTIVE" = false ] && [ "$FIREWALLD_ACTIVE" = false ] && [ "$IPTABLES_ACTIVE" = false ]; then
        info "未检测到活跃防火墙，跳过端口放行"
        return 0
    fi

    echo ""
    warn "检测到活跃防火墙，是否自动放行新端口 ${PORT}/tcp？"
    read -rp "  自动放行？(Y/n，默认Y): " FW_CONFIRM
    FW_CONFIRM="${FW_CONFIRM:-y}"
    if ! echo "$FW_CONFIRM" | grep -qiE '^y(es)?$'; then
        warn "已跳过，请在防火墙管理中手动添加端口 $PORT"
        return 0
    fi

    if [ "$UFW_ACTIVE" = true ]; then
        ufw allow "${PORT}"/tcp 2>/dev/null && info "ufw 已放行 ${PORT}/tcp ✓"
    fi
    if [ "$FIREWALLD_ACTIVE" = true ]; then
        firewall-cmd --permanent --add-port="${PORT}/tcp" 2>/dev/null &&         firewall-cmd --reload 2>/dev/null &&         info "firewalld 已放行 ${PORT}/tcp ✓"
    fi
    if [ "$IPTABLES_ACTIVE" = true ]; then
        iptables -I INPUT -p tcp --dport "$PORT" -j ACCEPT
        [ -f /etc/iptables/rules.v4 ] && iptables-save > /etc/iptables/rules.v4
        info "iptables 已放行 ${PORT}/tcp ✓"
    fi
}
